import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { prisma } from "@/lib/db/client";
import { GrowthAttribution } from "@/components/GrowthAttribution";
import { COLORS, money, publicBaseUrl, snapshotOutlook, timestamp, type ResearchSnapshot } from "@/lib/growth/research";
import { SignalPriceOutlook } from "@/components/SignalPriceOutlook";
export const dynamic = "force-dynamic";
type Props = { params: Promise<{ id: string }> };
async function read(id: string) { if (!/^[a-z0-9]{20,40}$/.test(id)) return null; return prisma.socialSignal.findUnique({ where: { id } }); }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params; const row = await read(id); if (!row) return { title: "Research unavailable · Swing Up" };
  const snapshot = row.snapshot as unknown as ResearchSnapshot;
  return { title: `${snapshot.ticker}: ${snapshot.label} · Swing Up`, description: snapshot.title, openGraph: { title: snapshot.title, description: "Dated provisional research, model valuation and risk context.", images: [{ url: `${publicBaseUrl()}/api/public/social-image/${id}`, width: 1080, height: 1350 }] }, twitter: { card: "summary_large_image" } };
}
export default async function ResearchDetail({ params }: Props) {
  const { id } = await params; const row = await read(id); if (!row) notFound();
  const s = row.snapshot as unknown as ResearchSnapshot;
  return <div className="page launch-page"><GrowthAttribution /><Link href="/research" className="muted">← Research history</Link><div className="launch-heading" style={{ marginTop: 28 }}><span className="research-badge" style={{ color: COLORS[s.action] }}>{s.label} · {s.committeeApproved ? "Committee approved" : "Provisional alert"}</span><h1>{s.title}</h1><p>{s.company} · USD · Valuation-screen observation</p></div><div className="research-detail"><article className="card"><SignalPriceOutlook outlook={snapshotOutlook(s)} action={s.action} /><h2>What the company does</h2><p>{s.companyDoes ?? "This older snapshot does not include a verified company description."}</p><h2>What is happening</h2><p>{s.whatHappened ?? `${s.title}. This is a model comparison; a new company event has not been established.`}</p><h2>Why the system flagged it</h2><p>{s.why}</p><h2>What could happen next</h2><p>{s.expected}</p><h2>What could go wrong</h2><p>{s.risk}</p><div className="research-disclaimer">This model has not established a probability of profit or a forecast date. A sell-research label is a general valuation observation, not an instruction to sell your holdings. {s.committeeApproved ? "This snapshot records Committee approval; newer prices or facts may change the assessment." : "This snapshot has not received Committee approval."}</div>
      <details><summary>Sources</summary><p className="muted">These links help you inspect the market and filings. They are not verified receipts for a new news event.</p><ul>{s.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.label} ↗</a></li>)}</ul></details>{s.methods.length > 0 && <details><summary>Stored model methods</summary><ul>{s.methods.map((method, index) => <li key={index}>{method}</li>)}</ul></details>}</article>
      <aside className="card launch-form"><h2>The model, at a glance</h2><div><strong>Confidence: {s.confidence}/100</strong><div className="research-confidence" style={{ marginTop: 12 }}><span style={{ width: `${s.confidence}%` }} /></div><small className="muted">Model confidence, not the chance of profit.</small></div><p>Model range<br /><strong>{money(s.low)} – {money(s.high)}</strong></p><p>Risk score: <strong>{s.riskScore ?? "Unavailable"}/100</strong><br /><small className="muted">Higher means more model-assessed risk.</small></p><div className="research-times"><span>Price collected: {timestamp(s.priceObservedAt)}</span><span>Screen observed: {timestamp(s.observedAt)}</span><span>Snapshot saved: {timestamp(s.capturedAt)}</span><span>News event time: not established</span><span>Price is a recorded observation, not a live quote.</span></div><h2>Get the full picture at launch.</h2><p>Join early-bird access for the full signal experience when Swing Up launches.</p><Link className="button primary" href="/signup">Join early access</Link><a className="button" href={`/api/public/social-image/${id}`} target="_blank" rel="noopener noreferrer">View the social card</a><small className="muted">Know your moves before the market does.</small></aside></div></div>;
}
