export default function PrivacyPage() {
  return <div className="page launch-page"><article className="card launch-narrow"><span className="eyebrow">Updated 14 September 2026</span><h1>Early-access privacy</h1>
    <h2>What we save</h2><p>When you join, Swing Up saves your email, optional product feedback, free or paid-pilot preference, proposed price, consent date and version, and the social channel or research link that brought you here. This is an early-access request, not a product account or a purchase.</p>
    <h2>Why we use it</h2><p>We use signup details to evaluate interest, plan the pilot and send the early-access and launch updates you requested. We do not sell this signup information or use it for unrelated advertising. Email verification and automatic email delivery are not active at this stage.</p>
    <h2>Visits and security</h2><p>The browser keeps a temporary session identifier and referral channel until the browser session ends. We count visits by channel and research link; these counts can include bots and repeat visitors. We use short-lived hashed network identifiers to limit abusive form requests. We do not store raw IP addresses in the signup database. Hosting providers may retain operational request logs under their own settings.</p>
    <h2>Storage and retention</h2><p>Signup details are stored with our hosting and database provider, Railway. Visit records are removed after 90 days, signup records after 12 months, and request-limit records after expiry. Public research snapshots contain company research, not your signup details. Platform and infrastructure logs and backups can have separate retention periods.</p>
    <h2>Withdraw and delete</h2><p>Save the private deletion link shown after your first signup. Opening it and selecting “Delete my signup” removes the associated record and withdraws permission for updates. Keep this link private. A repeat submission does not replace your original link or preferences. Self-service recovery of a lost link is not available yet.</p>
    <h2>Payments and external links</h2><p>We collect no card details and charge nothing through the early-access form. Market-data, filing and social links lead to other services governed by their own policies.</p>
  </article></div>;
}
