import Link from "next/link";
import { GrowthAttribution } from "@/components/GrowthAttribution";
import { ResearchCard } from "@/components/ResearchCard";
import { latestResearch } from "@/lib/growth/public-records";
export const dynamic = "force-dynamic";
export default async function Home() {
  const research = await latestResearch(3);
  return <div className="page launch-page"><GrowthAttribution /><section className="launch-heading"><span className="eyebrow">Swing Up · Stock research, in context</span><h1>Know your moves before the market does.</h1><p className="launch-intro">Understand the opportunity. Question the assumptions. See the risk. Provisional stock research with the price, reasoning and model valuation in one clear view.</p><div className="button-row"><Link className="button primary" href="/signup">Get early-bird access</Link><Link className="button" href="/research">Explore the research</Link></div><p className="muted">Join the launch list for the full signal experience. No card required.</p></section>
    <section aria-label="Latest research"><div className="button-row" style={{ justifyContent: "space-between", marginBottom: 24 }}><h2>See what the model is watching</h2><span className="badge">Provisional research</span></div>{research.rows.length ? <div className="research-grid">{research.rows.map((row) => <ResearchCard key={row.id} id={row.id} snapshot={row.snapshot} />)}</div> : <div className="card"><h2>{research.available ? "The first research snapshots are being prepared." : "Research is temporarily unavailable."}</h2><p>Join early access while we prepare fresh, dated observations.</p><Link className="button" href="/signup">Join early access</Link></div>}</section>
    <section className="grid three" style={{ marginTop: 48 }}><article className="card"><span className="eyebrow">01 · Context</span><h2>A reason, not just a ticker.</h2><p>Read why a company enters the screen and what would need to happen for the model’s scenario to play out.</p></article><article className="card"><span className="eyebrow">02 · Uncertainty</span><h2>Risk stays in view.</h2><p>Model confidence, valuation ranges and missing catalysts are visible. An estimate is never a guaranteed price move.</p></article><article className="card"><span className="eyebrow">03 · The record</span><h2>Check what we said.</h2><p>Saved snapshots keep their original price and time. Follow the source links and inspect the research history.</p></article></section>
    <section className="card" style={{ marginTop: 40 }}><h2>Would this help you make a more informed decision?</h2><p>We’re testing real demand before building more. Join free early access or tell us if you would consider a $19/month pilot. No payment is taken.</p><Link className="button primary" href="/signup">Help shape Swing Up</Link></section>
    <p className="research-disclaimer">Swing Up provides general, provisional research. Model targets have no established time horizon, and confidence scores are not probabilities of profit. Nothing here is personalized financial advice or a promise of returns.</p><footer className="research-footer"><Link href="/research">Research history</Link><Link href="/pricing">Pilot pricing</Link><Link href="/privacy">Privacy</Link><Link href="/methodology">Methodology</Link></footer>
  </div>;
}
