import crypto from "node:crypto";
import { prisma } from "@/lib/db/client";

const TRACKING_PARAMS = new Set(["utm_source","utm_medium","utm_campaign","utm_term","utm_content","fbclid","gclid","mc_cid","mc_eid"]);
const MAX_FETCH_MS = 5000;
const MAX_TEXT = 24000;
const MAX_SUMMARY = 1800;

type ArticleInput = { articleUrl?: string | null; title?: string | null; snippet?: string | null; source?: string | null; ticker?: string | null; company?: string | null; receivedAt?: Date | string | null; confirmRun?: boolean; dryRun?: boolean; duplicateArticleSourceId?: string | null };
export type ArticleMemoryResult = Record<string, unknown>;

function text(v: unknown, max = 1000) { return typeof v === "string" ? v.trim().slice(0, max) : ""; }
function hash(v: string) { return crypto.createHash("sha256").update(v).digest("hex"); }
export function normalizeArticleUrl(url: string) {
  try {
    const parsed = new URL(url);
    parsed.hash = "";
    for (const key of Array.from(parsed.searchParams.keys())) if (TRACKING_PARAMS.has(key.toLowerCase())) parsed.searchParams.delete(key);
    parsed.searchParams.sort();
    return parsed.toString();
  } catch { return url.trim(); }
}
export function articleIdentity(input: ArticleInput) {
  const articleUrl = text(input.articleUrl, 3000);
  const normalizedArticleUrl = articleUrl ? normalizeArticleUrl(articleUrl) : "";
  const articleUrlHash = normalizedArticleUrl ? hash(normalizedArticleUrl) : "";
  const title = text(input.title, 1000);
  const titleHash = title ? hash(title.toLowerCase()) : "";
  return { articleUrl, normalizedArticleUrl, articleUrlHash, canonicalArticleId: articleUrlHash || titleHash, sourceName: text(input.source, 200), titleHash, firstSeenAt: input.receivedAt ?? new Date(), lastSeenAt: new Date() };
}
function emptyResult(input: ArticleInput) { const id = articleIdentity(input); return { ...id, hasArticleUrl: Boolean(id.articleUrl), articleAlreadySeen: false, articleMemoryAvailable: false, articleMemoryUsed: false, reusedArticleMemoryId: null as string | null, articleReadAttempted: false, articleTextAvailable: false, articleTextLength: 0, articleTextStored: false, articleSummaryAvailable: false, articleInputMode: id.articleUrl ? "not_read" : "title_snippet_only", articleSummary: "", relevanceSummary: "", catalystSummary: "", proofSummary: "", riskSummary: "", entitiesDetected: [] as string[], topicsDetected: [] as string[], articleRelevanceScore: 0, articleQualityScore: 0, aiArticleSummaryUsed: false, aiArticleSummaryReason: "confirmRun=false_or_ai_not_enabled", errorCategory: null as string | null, errorMessageSafe: null as string | null, articleMemoryProofUsed: false, articleMemoryProofReason: null as string | null, articleMemoryRejectedReason: "not_evaluated", duplicateArticleInRun: false, duplicateArticleSourceId: input.duplicateArticleSourceId ?? null, duplicateArticleReuseReason: null as string | null }; }
export async function ensureArticleMemoryTable() { await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS article_memory (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), article_url_hash text UNIQUE NOT NULL, normalized_url text NOT NULL, source_name text, title text, title_hash text, ticker_symbols jsonb DEFAULT '[]', company_names jsonb DEFAULT '[]', article_text_available boolean DEFAULT false, article_text_read boolean DEFAULT false, article_text_read_at timestamptz, article_summary text, relevance_summary text, catalyst_summary text, proof_summary text, risk_summary text, entities_detected jsonb DEFAULT '[]', topics_detected jsonb DEFAULT '[]', article_relevance_score integer DEFAULT 0, article_quality_score integer DEFAULT 0, article_duplicate_of text, first_seen_at timestamptz DEFAULT now(), last_seen_at timestamptz DEFAULT now(), read_count integer DEFAULT 0, reused_count integer DEFAULT 0, raw_text_storage_ref text, error_category text, error_message_safe text); CREATE INDEX IF NOT EXISTS article_memory_seen_idx ON article_memory(last_seen_at DESC);`); }
async function findMemory(articleUrlHash: string) { await ensureArticleMemoryTable(); const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(`SELECT * FROM article_memory WHERE article_url_hash=$1 LIMIT 1`, articleUrlHash); return rows[0] ?? null; }
async function upsertMemory(input: ArticleInput, r: Record<string, unknown>) { await ensureArticleMemoryTable(); const id = articleIdentity(input); await prisma.$executeRawUnsafe(`INSERT INTO article_memory(article_url_hash,normalized_url,source_name,title,title_hash,ticker_symbols,company_names,article_text_available,article_text_read,article_text_read_at,article_summary,relevance_summary,catalyst_summary,proof_summary,risk_summary,entities_detected,topics_detected,article_relevance_score,article_quality_score,first_seen_at,last_seen_at,read_count,reused_count,error_category,error_message_safe) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,now(),$10,$11,$12,$13,$14,$15::jsonb,$16::jsonb,$17,$18,now(),now(),1,0,$19,$20) ON CONFLICT(article_url_hash) DO UPDATE SET last_seen_at=now(), source_name=EXCLUDED.source_name, title=EXCLUDED.title, article_summary=EXCLUDED.article_summary, relevance_summary=EXCLUDED.relevance_summary, catalyst_summary=EXCLUDED.catalyst_summary, proof_summary=EXCLUDED.proof_summary, risk_summary=EXCLUDED.risk_summary, article_text_available=EXCLUDED.article_text_available, article_text_read=EXCLUDED.article_text_read, read_count=article_memory.read_count+1, error_category=EXCLUDED.error_category, error_message_safe=EXCLUDED.error_message_safe`, id.articleUrlHash, id.normalizedArticleUrl, id.sourceName, text(input.title,1000), id.titleHash, JSON.stringify(input.ticker?[input.ticker]:[]), JSON.stringify(input.company?[input.company]:[]), Boolean(r.articleTextAvailable), Boolean(r.articleReadAttempted), r.articleSummary ?? "", r.relevanceSummary ?? "", r.catalystSummary ?? "", r.proofSummary ?? "", r.riskSummary ?? "", JSON.stringify(r.entitiesDetected ?? []), JSON.stringify(r.topicsDetected ?? []), r.articleRelevanceScore ?? 0, r.articleQualityScore ?? 0, r.errorCategory ?? null, r.errorMessageSafe ?? null); return findMemory(id.articleUrlHash); }
export async function markMemoryReused(articleUrlHash: string) { await ensureArticleMemoryTable(); await prisma.$executeRawUnsafe(`UPDATE article_memory SET reused_count=reused_count+1,last_seen_at=now() WHERE article_url_hash=$1`, articleUrlHash); }
function extractHtmlText(html: string) { return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim().slice(0, MAX_TEXT); }
async function fetchArticle(url: string) { const controller = new AbortController(); const timer = setTimeout(()=>controller.abort(), MAX_FETCH_MS); try { const res = await fetch(url,{signal:controller.signal,headers:{"user-agent":"SwingUpArticleReader/1.0 (+internal research memory; no paywall bypass)"}}); if (!res.ok) return { text:"", errorCategory:`http_${res.status}`, errorMessageSafe:`Article fetch returned HTTP ${res.status}`}; const ct=res.headers.get("content-type")||""; if(!/html|text|xml/.test(ct)) return {text:"", errorCategory:"unsupported_content_type", errorMessageSafe:"Article content type is not readable text/html"}; return { text: extractHtmlText(await res.text()) }; } catch(e) { return { text:"", errorCategory:"fetch_failed", errorMessageSafe: e instanceof Error && e.name === "AbortError" ? "article_fetch_timeout" : "article_fetch_failed" }; } finally { clearTimeout(timer); } }
function deterministic(input: ArticleInput, fullText: string) { const base = [text(input.title,300), text(input.snippet,700), fullText.slice(0,1800)].filter(Boolean).join(" "); const lower=base.toLowerCase(); const keywords=["earnings","guidance","merger","acquisition","fda","approval","lawsuit","sec","contract","partnership","recall","investigation","tariff","rates","revenue","profit","forecast"].filter(k=>lower.includes(k)); const entities=[text(input.ticker,20),text(input.company,120)].filter(Boolean); const score=Math.min(100, 20 + (fullText?35:0) + keywords.length*5 + (entities.length?15:0)); return { articleSummary: (base || "No article text was available; using title/snippet only.").slice(0,MAX_SUMMARY), relevanceSummary: entities.length ? `Relevant because it mentions or is attached to ${entities.join(" / ")}.` : "Relevance is limited to the supplied headline, snippet, URL, and source metadata.", catalystSummary: keywords.length ? `Potential catalyst keywords detected: ${keywords.join(", ")}.` : "No strong deterministic catalyst keywords found.", proofSummary: fullText ? "Full article text was fetched and summarized deterministically; this can strengthen news proof but cannot create an alert alone." : "articleInputMode = title_snippet_only; full article text was unavailable, so proof support is limited.", riskSummary: /opinion|rumor|rumour|blog|analysis/.test(lower) ? "May be opinion or analysis; needs another clean proof type." : "No deterministic paywall bypass or private data used; still requires independent proof before promotion.", entitiesDetected: entities, topicsDetected: keywords, articleRelevanceScore: score, articleQualityScore: Math.min(100, (fullText.length>1000?60:30)+keywords.length*4) }; }
export async function readArticleForMemory(input: ArticleInput): Promise<ArticleMemoryResult> { const base=emptyResult(input); if(!base.hasArticleUrl) return {...base, errorCategory:"no_url", errorMessageSafe:"No article URL supplied"}; const existing=await findMemory(base.articleUrlHash); if(existing?.article_summary){ await markMemoryReused(base.articleUrlHash); return {...base, articleAlreadySeen:true, articleMemoryAvailable:true, articleMemoryUsed:true, reusedArticleMemoryId:String(existing.id), articleReadAttempted:false, articleTextAvailable:Boolean(existing.article_text_available), articleSummaryAvailable:true, articleInputMode: existing.article_text_available ? "memory_full_text_summary" : "memory_title_snippet_only", reusedArticleSummary:String(existing.article_summary ?? ""), reusedCatalystSummary:String(existing.catalyst_summary ?? ""), reusedRelevanceSummary:String(existing.relevance_summary ?? ""), reusedProofSummary:String(existing.proof_summary ?? ""), reusedRiskSummary:String(existing.risk_summary ?? ""), articleSummary:String(existing.article_summary ?? ""), catalystSummary:String(existing.catalyst_summary ?? ""), relevanceSummary:String(existing.relevance_summary ?? ""), proofSummary:String(existing.proof_summary ?? ""), riskSummary:String(existing.risk_summary ?? "")}; }
 const blocked=/bloomberg|wsj\.com|ft\.com|nytimes\.com\/subscription|seekingalpha/i.test(base.normalizedArticleUrl); if(blocked) return {...base, errorCategory:"blocked_or_paywalled", errorMessageSafe:"Source appears paywalled or blocked; no bypass attempted"};
 const fetched=await fetchArticle(base.normalizedArticleUrl); const fullText=fetched.text || ""; const summaries=deterministic(input, fullText); const result={...base,...summaries, articleReadAttempted:true, articleTextAvailable:fullText.length>250, articleTextLength:fullText.length, articleTextStored:false, articleSummaryAvailable:true, articleInputMode: fullText.length>250 ? "full_text" : "title_snippet_only", errorCategory:fetched.errorCategory ?? null, errorMessageSafe:fetched.errorMessageSafe ?? null, articleMemoryProofUsed: summaries.articleRelevanceScore>=50, articleMemoryProofReason: summaries.articleRelevanceScore>=50 ? "Article summary matches ticker/company/topic and can strengthen news proof only." : null, articleMemoryRejectedReason: summaries.articleRelevanceScore>=50 ? null : "article_summary_not_relevant_enough"};
 const stored=await upsertMemory(input,result); return {...result, articleTextStored:Boolean(stored), articleMemoryAvailable:Boolean(stored)};
}
export async function latestArticleSignals(limit:number) { return prisma.rawSignal.findMany({ where:{ sourceUrl:{not:null}}, orderBy:[{receivedAt:"desc"}], take: Math.max(1, Math.min(limit,20)), select:{id:true,source:true,ticker:true,title:true,summary:true,sourceUrl:true,receivedAt:true,payload:true} }); }
