import { getR2Config } from "@/lib/r2-warehouse";

export type EarStatus = "connected" | "degraded" | "failed" | "planned" | "blocked" | "not_configured";
export type EarRegistryEntry = {
  layerNumber: number;
  layerName: string;
  tier: "Tier 1" | "Tier 2" | "Core";
  earName: string;
  sourceProvider: string;
  status: EarStatus;
  canImplementNow: boolean;
  blocker: string | null;
  howToSolve: string | null;
  dataCaptured: string[];
  proofTypesProduced: string[];
  assetTypes: string[];
  historyDepth: string;
  rateLimitRisk: "low" | "medium" | "high";
  noiseRisk: "low" | "medium" | "high";
  priority: "critical" | "high" | "medium" | "low";
  r2RawStorageEnabled: boolean;
};

export const EAR_LAYERS = [
  { layerNumber: 1, layerName: "Official truth" },
  { layerNumber: 2, layerName: "Fast market news" },
  { layerNumber: 3, layerName: "Money movement" },
  { layerNumber: 4, layerName: "Business quality" },
  { layerNumber: 5, layerName: "Real-world demand" },
  { layerNumber: 6, layerName: "Risk detector" },
  { layerNumber: 7, layerName: "Historical memory" },
] as const;

const r2Enabled = () => getR2Config().configured;
const has = (name: string) => Boolean(process.env[name]?.trim());
function entry(input: Omit<EarRegistryEntry, "r2RawStorageEnabled"> & { r2RawStorageEnabled?: boolean }): EarRegistryEntry {
  return { ...input, r2RawStorageEnabled: input.r2RawStorageEnabled ?? r2Enabled() };
}

export function buildEarRegistry(): EarRegistryEntry[] {
  const fmpConfigured = has("FMP_API_KEY");
  const alphaConfigured = has("ALPHA_VANTAGE_API_KEY");
  const polygonConfigured = has("POLYGON_API_KEY");
  return [
    entry({ layerNumber: 1, layerName: "Official truth", tier: "Core", earName: "SEC EDGAR Filings Ear", sourceProvider: "SEC EDGAR public APIs", status: "connected", canImplementNow: true, blocker: null, howToSolve: null, dataCaptured: ["ticker", "CIK", "form type", "filing date", "SEC filing URL", "accession number"], proofTypesProduced: ["filing", "raw_signal_source"], assetTypes: ["stocks"], historyDepth: "SEC submissions recent filings plus archives as requested", rateLimitRisk: "medium", noiseRisk: "medium", priority: "critical" }),
    entry({ layerNumber: 1, layerName: "Official truth", tier: "Tier 1", earName: "SEC 8-K Material Event Classifier", sourceProvider: "SEC EDGAR 8-K filings", status: "connected", canImplementNow: true, blocker: null, howToSolve: null, dataCaptured: ["contracts", "guidance", "leadership changes", "auditor changes", "debt/default", "investigation", "litigation", "acquisition/disposition", "financing/dilution", "material agreement", "risk warning"], proofTypesProduced: ["filing"], assetTypes: ["stocks"], historyDepth: "Current recent filings; full archive available by accession", rateLimitRisk: "medium", noiseRisk: "medium", priority: "critical" }),
    entry({ layerNumber: 3, layerName: "Money movement", tier: "Tier 1", earName: "Insider Cluster Buying Ear", sourceProvider: "SEC Form 4", status: "degraded", canImplementNow: true, blocker: "Form 4 filings are ingested, but XML ownership transaction parsing and cluster aggregation are partial.", howToSolve: "Add Form 4 XML transaction parser, issuer/officer role extraction, cluster windows, ownership percentage deltas, and follow-up outcome jobs.", dataCaptured: ["ticker", "insider name", "role", "buy/sell", "transaction size", "ownership change", "cluster count", "date", "SEC filing URL"], proofTypesProduced: ["filing"], assetTypes: ["stocks"], historyDepth: "Recent SEC submissions now; archive backfill planned", rateLimitRisk: "medium", noiseRisk: "medium", priority: "critical" }),
    entry({ layerNumber: 1, layerName: "Official truth", tier: "Tier 1", earName: "ClinicalTrials.gov Ear", sourceProvider: "ClinicalTrials.gov API v2", status: "planned", canImplementNow: true, blocker: "Ticker mapping from sponsor names is not strong enough for automatic promotion yet.", howToSolve: "Use ClinicalTrials.gov API v2 for safe pulls, map sponsors through SEC/Wikidata/company aliases, and require trial URL plus same-company proof before promotion.", dataCaptured: ["trial status", "phase", "sponsor", "condition", "intervention", "completion date", "results posted", "enrollment change", "ticker mapping"], proofTypesProduced: ["news", "raw_signal_source"], assetTypes: ["stocks", "biotech"], historyDepth: "API supports current and historical study records", rateLimitRisk: "low", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 1, layerName: "Official truth", tier: "Tier 1", earName: "Government Contracts Ear", sourceProvider: "USAspending.gov / SAM.gov official APIs", status: "planned", canImplementNow: true, blocker: "Recipient-to-public-ticker mapping and duplicate award normalization are not production-ready.", howToSolve: "Implement USAspending award search, cache raw award JSON in R2, map recipients using UEI/CAGE/company aliases, and require official award URL proof.", dataCaptured: ["award date", "recipient", "amount", "agency", "contract title", "sector", "ticker mapping", "repeated awards"], proofTypesProduced: ["news", "raw_signal_source"], assetTypes: ["stocks"], historyDepth: "USAspending historical awards by API limits", rateLimitRisk: "medium", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 3, layerName: "Money movement", tier: "Tier 1", earName: "Politician / Congressional Trades Ear", sourceProvider: "Quiver Quant, Capitol Trades, House/Senate disclosures, licensed API", status: "blocked", canImplementNow: false, blocker: "No reliable free API with acceptable licensing is configured; scraping House/Senate PDFs at scale needs terms/legal review and robust parsing.", howToSolve: "Use a licensed provider such as Quiver Quant or Capitol Trades, or build an official-disclosure parser after legal review; store raw filings in R2 and require disclosure URL proof.", dataCaptured: ["politician", "chamber", "party", "committee", "ticker", "company", "transaction type", "amount range", "transaction date", "disclosure date", "filing delay", "sector/policy", "repeat pattern", "7/30/90 day follow-up"], proofTypesProduced: ["filing", "raw_signal_source"], assetTypes: ["stocks"], historyDepth: "Provider/license dependent", rateLimitRisk: "medium", noiseRisk: "high", priority: "critical", r2RawStorageEnabled: false }),
    entry({ layerNumber: 4, layerName: "Business quality", tier: "Tier 1", earName: "Earnings Transcript Tone Ear", sourceProvider: "FMP transcripts", status: fmpConfigured ? "degraded" : "not_configured", canImplementNow: fmpConfigured, blocker: fmpConfigured ? "FMP endpoint/plan must be verified before using transcript text." : "FMP_API_KEY is not configured.", howToSolve: "Verify FMP transcript endpoint access; store raw transcript in R2; extract demand, margin, backlog, pricing power, caution words, and quote references without fabricating text.", dataCaptured: ["demand language", "margin language", "guidance tone", "backlog", "pricing power", "caution words", "CEO/CFO quotes"], proofTypesProduced: ["news", "fundamentals"], assetTypes: ["stocks"], historyDepth: "FMP plan dependent", rateLimitRisk: "medium", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 4, layerName: "Business quality", tier: "Tier 1", earName: "Analyst Estimate Revision Ear", sourceProvider: "Alpha Vantage / FMP", status: alphaConfigured || fmpConfigured ? "degraded" : "not_configured", canImplementNow: alphaConfigured || fmpConfigured, blocker: alphaConfigured || fmpConfigured ? "Estimate fields vary by provider plan and must be validated per endpoint." : "No Alpha Vantage or FMP key configured.", howToSolve: "Validate provider endpoints for EPS/revenue estimates, price targets, ratings, analyst count, and persist only returned values.", dataCaptured: ["EPS estimate revision", "revenue revision", "price target", "rating", "direction", "analyst count"], proofTypesProduced: ["fundamentals", "news"], assetTypes: ["stocks"], historyDepth: "Provider plan dependent", rateLimitRisk: "medium", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 1", earName: "Supply Chain / Customer Graph Ear", sourceProvider: "Wikidata public mappings", status: "degraded", canImplementNow: true, blocker: "Public graph confidence is useful for context but weak for automatic ticker-level proof.", howToSolve: "Combine Wikidata with company filings/customer disclosures and confidence-score each edge before attaching proof.", dataCaptured: ["supplier", "customer", "competitor", "industry exposure", "affected ticker", "confidence score"], proofTypesProduced: ["news"], assetTypes: ["stocks", "crypto"], historyDepth: "Current public graph snapshots", rateLimitRisk: "low", noiseRisk: "high", priority: "medium" }),
    entry({ layerNumber: 2, layerName: "Fast market news", tier: "Core", earName: "Fast Market News Ears", sourceProvider: "Marketaux, Alpha Vantage, Google News RSS, GDELT, FMP", status: "degraded", canImplementNow: true, blocker: "Some providers require API keys or have plan limits; Google/GDELT are noisy.", howToSolve: "Keep tiny pulls, require ticker/company/topic proof matching, and never promote generic market headlines.", dataCaptured: ["headline", "summary", "URL", "published time", "ticker/company when available"], proofTypesProduced: ["news", "raw_signal_source"], assetTypes: ["stocks", "crypto", "macro"], historyDepth: "Provider dependent; GDELT/Google current windows", rateLimitRisk: "medium", noiseRisk: "high", priority: "critical" }),
    entry({ layerNumber: 3, layerName: "Money movement", tier: "Tier 2", earName: "Short Interest / Borrow Cost Ear", sourceProvider: "FINRA short sale files; paid borrow providers", status: "degraded", canImplementNow: true, blocker: "FINRA short volume is available; true short interest, borrow cost, and utilization need licensed data.", howToSolve: "Use FINRA for short volume and add Ortex/S3/IBKR-style licensed borrow feed for cost/utilization.", dataCaptured: ["short volume", "short interest", "borrow cost", "utilization"], proofTypesProduced: ["price_volume"], assetTypes: ["stocks"], historyDepth: "FINRA daily files; paid source dependent", rateLimitRisk: "low", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 3, layerName: "Money movement", tier: "Tier 2", earName: "Options Flow Ear", sourceProvider: "Unusual Whales / Polygon / Tradier / licensed OPRA-style feed", status: polygonConfigured ? "planned" : "blocked", canImplementNow: false, blocker: "Unusual options sweep/block data is usually paid/licensed and no production provider is configured.", howToSolve: "Add licensed options-flow provider and capture unusual call/put volume, sweeps, IV, OI, expiry, strike, sentiment with exchange receipts where allowed.", dataCaptured: ["call/put volume", "sweeps", "blocks", "IV", "OI", "expiry", "strike", "sentiment"], proofTypesProduced: ["price_volume"], assetTypes: ["stocks", "options"], historyDepth: "Provider/license dependent", rateLimitRisk: "high", noiseRisk: "high", priority: "high", r2RawStorageEnabled: false }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 2", earName: "Patent Filings Ear", sourceProvider: "PatentsView / USPTO", status: "planned", canImplementNow: true, blocker: "Assignee-to-public-ticker mapping and keyword taxonomy need validation before auto-promotion.", howToSolve: "Use PatentsView/USPTO APIs, store raw patent records in R2, map assignees via company aliases, and treat as early weak demand/innovation proof until corroborated.", dataCaptured: ["assignee", "title", "technology keywords", "filing date", "publication date", "ticker mapping"], proofTypesProduced: ["news", "raw_signal_source"], assetTypes: ["stocks"], historyDepth: "USPTO/PatentsView historical records", rateLimitRisk: "medium", noiseRisk: "medium", priority: "medium" }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 2", earName: "Job Posting Acceleration Ear", sourceProvider: "Licensed jobs API / company career pages after terms review", status: "blocked", canImplementNow: false, blocker: "No reliable licensed jobs feed is configured; broad scraping may violate terms.", howToSolve: "Use a licensed jobs dataset/API or explicit company feeds; capture snapshots in R2 and compare category/location trends.", dataCaptured: ["company", "role category", "location", "acceleration/deceleration", "source"], proofTypesProduced: ["news"], assetTypes: ["stocks"], historyDepth: "Provider dependent", rateLimitRisk: "high", noiseRisk: "high", priority: "medium", r2RawStorageEnabled: false }),
    entry({ layerNumber: 3, layerName: "Money movement", tier: "Tier 2", earName: "ETF / Sector Flow Ear", sourceProvider: "Polygon/Alpha/FMP market data plus ETF holdings", status: polygonConfigured || alphaConfigured || fmpConfigured ? "planned" : "not_configured", canImplementNow: polygonConfigured || alphaConfigured || fmpConfigured, blocker: "ETF holdings/flow endpoint must be validated; price moves are bonus confirmation only.", howToSolve: "Pull sector ETF movement, peer moves, and holdings from configured market data without making market reaction mandatory.", dataCaptured: ["sector ETF movement", "holdings", "industry strength", "peer moves", "sector rotation"], proofTypesProduced: ["price_volume"], assetTypes: ["stocks", "ETF"], historyDepth: "Provider dependent", rateLimitRisk: "medium", noiseRisk: "medium", priority: "medium" }),
    entry({ layerNumber: 6, layerName: "Risk detector", tier: "Tier 2", earName: "Lawsuit / Investigation Ear", sourceProvider: "SEC/DOJ/FTC/enforcement pages, CourtListener planned", status: "planned", canImplementNow: true, blocker: "Ticker mapping and legal-source normalization are not finished.", howToSolve: "Use official enforcement feeds and CourtListener where allowed; require real docket/enforcement URL and same-company matching.", dataCaptured: ["lawsuit", "SEC/DOJ/FTC investigation", "class action", "enforcement", "risk severity", "ticker mapping"], proofTypesProduced: ["news", "filing"], assetTypes: ["stocks"], historyDepth: "Source dependent", rateLimitRisk: "medium", noiseRisk: "medium", priority: "high" }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 2", earName: "Product Pricing Change Monitor", sourceProvider: "Official product pages after terms review", status: "planned", canImplementNow: false, blocker: "Automated product-page monitoring needs source-by-source terms review and stable selectors.", howToSolve: "Use official APIs/feeds or approved monitoring; store page snapshots in R2 and attach exact product URL proof.", dataCaptured: ["price increase/decrease", "product page change", "subscription price change", "margin impact"], proofTypesProduced: ["news"], assetTypes: ["stocks"], historyDepth: "Starts after approved snapshot baseline", rateLimitRisk: "medium", noiseRisk: "high", priority: "medium", r2RawStorageEnabled: false }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 2", earName: "App Ranking / Product Review Ear", sourceProvider: "Data.ai / Sensor Tower / official app-store APIs", status: "blocked", canImplementNow: false, blocker: "No licensed app rank/review provider is configured.", howToSolve: "Add licensed provider or official API access; capture rank, ratings, reviews, volume with source receipts.", dataCaptured: ["app rank", "review trend", "rating change", "review volume"], proofTypesProduced: ["news"], assetTypes: ["stocks"], historyDepth: "Provider dependent", rateLimitRisk: "medium", noiseRisk: "high", priority: "medium", r2RawStorageEnabled: false }),
    entry({ layerNumber: 5, layerName: "Real-world demand", tier: "Tier 2", earName: "Web/App Traffic Ear", sourceProvider: "Similarweb / Data.ai / Sensor Tower", status: "blocked", canImplementNow: false, blocker: "Traffic and engagement data is usually paid/licensed; no provider configured.", howToSolve: "Add Similarweb/Data.ai/Sensor Tower style provider and store permitted raw responses in R2.", dataCaptured: ["traffic growth", "engagement change", "app usage"], proofTypesProduced: ["news"], assetTypes: ["stocks"], historyDepth: "Provider dependent", rateLimitRisk: "high", noiseRisk: "medium", priority: "medium", r2RawStorageEnabled: false }),
    entry({ layerNumber: 7, layerName: "Historical memory", tier: "Core", earName: "Historical Memory Ear", sourceProvider: "Stored raw signals, pattern matcher, price/macro history", status: "degraded", canImplementNow: true, blocker: "Only stored patterns can be used; no fake historical matches are allowed.", howToSolve: "Backfill source-by-source into R2/PostgreSQL indexes and compare as far back as each provider honestly allows.", dataCaptured: ["historical price patterns", "similar filing/news/earnings outcomes", "macro context", "sector/ETF history", "crypto/FX/macro histories"], proofTypesProduced: ["pattern_match"], assetTypes: ["stocks", "ETF", "crypto", "FX", "macro"], historyDepth: "As far back as stored/provider source allows", rateLimitRisk: "medium", noiseRisk: "medium", priority: "high" }),
  ];
}

export function earRegistrySummary() {
  const ears = buildEarRegistry();
  return {
    layers: EAR_LAYERS.map((layer) => ({ ...layer, ears: ears.filter((ear) => ear.layerNumber === layer.layerNumber).length })),
    totalEars: ears.length,
    connected: ears.filter((ear) => ear.status === "connected").length,
    degraded: ears.filter((ear) => ear.status === "degraded").length,
    blocked: ears.filter((ear) => ear.status === "blocked").length,
    planned: ears.filter((ear) => ear.status === "planned").length,
    notConfigured: ears.filter((ear) => ear.status === "not_configured").length,
    tier1: ears.filter((ear) => ear.tier === "Tier 1").length,
    tier2: ears.filter((ear) => ear.tier === "Tier 2").length,
  };
}
