import crypto from "node:crypto";
import { prisma } from "@/lib/db/client";
import { getR2OperationalStatus } from "@/lib/r2-warehouse";
import { redactSecrets } from "@/lib/redact-secrets";
import { getPriceVolumeProofForTicker } from "@/lib/price-volume-proof";

type Json = Record<string, unknown>;
type Candidate = { rawSignalId?: string; ticker: string; title?: string; sourceUrl?: string; stage?: string; proofTypes?: string[]; missingProof?: string[]; signalType?: string; summary?: string };
const FUNDAMENTALS_MAX_AGE_DAYS = 540;
const INSIDER_SIGNAL_TYPES = new Set(["insider_trade", "insider_buy", "insider_sell", "ownership_change", "money_movement"]);
const SEC_FORMS = new Set(["8-K","6-K","10-Q","10-K","4","13D","13G","S-1","S-3","424B","424B2","424B3","424B4","424B5","DEF 14A"]);
const RISK = ["lawsuit","investigation","probe","recall","warning letter","subpoena","antitrust","enforcement","fraud","accounting","auditor","going concern","dilution","offering","resignation","guidance cut","default","bankruptcy"];
const UA = { "User-Agent": process.env.SEC_USER_AGENT || "SwingUp proof recovery contact@example.com" };
const num = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : null;
const ticker = (v: unknown) => String(v ?? "").trim().toUpperCase().replace(/[^A-Z0-9.:-]/g, "").slice(0, 16);
async function fetchJson(url: string, headers: Record<string,string> = {}) { const r = await fetch(url,{headers:{...UA,...headers},cache:"no-store"}); if(!r.ok) throw new Error(`http_${r.status}`); return await r.json() as Json; }
let cikMapCache: Promise<Map<string,string>> | null = null;
async function cikMap() { if(!cikMapCache) cikMapCache = fetchJson("https://www.sec.gov/files/company_tickers.json").then(j=>{ const m=new Map<string,string>(); for(const v of Object.values(j) as Json[]) { const t=ticker(v.ticker); const cik=String(v.cik_str ?? "").padStart(10,"0"); if(t&&cik) m.set(t,cik); } return m; }).catch(()=>new Map()); return cikMapCache; }
async function tickerToCik(t: string) { return (await cikMap()).get(t) ?? null; }
function filingUrl(cik: string, accession: string, doc?: string) { const cleanCik=String(Number(cik)); const acc=accession.replace(/-/g,""); return `https://www.sec.gov/Archives/edgar/data/${cleanCik}/${acc}/${doc || `${accession}.txt`}`; }
function latestFacts(facts: Json, names: string[]) { const us = facts?.facts && typeof facts.facts === "object" ? (facts.facts as Json)["us-gaap"] as Json : null; const rows: Json[] = []; for(const name of names){ const units = us?.[name] && typeof us[name] === "object" ? (us[name] as Json).units as Json : null; for(const arr of Object.values(units ?? {}) as unknown[]){ if(Array.isArray(arr)){ rows.push(...(arr as Json[]).filter(x=>num(x.val)!==null && x.filed && ["10-Q","10-K"].includes(String(x.form ?? "")))); } } } rows.sort((a,b)=>`${String(b.filed)}:${String(b.end ?? "")}`.localeCompare(`${String(a.filed)}:${String(a.end ?? "")}`)); return rows[0] ?? null; }
function daysOld(date: unknown) { const time = Date.parse(String(date ?? "")); return Number.isFinite(time) ? (Date.now() - time) / 86400000 : Infinity; }
export async function recoverFundamentalsProof(t: string) { const symbol=ticker(t); const out: Json={ fundamentalsProofSource:null, fundamentalsProofAvailable:false, fundamentalsProofFresh:false, fundamentalsProofFieldsUsed:[], fundamentalsProofReceiptUrl:null, fundamentalsProofCompleteness:"unavailable", latestFiscalPeriod:null, formType:null, filedDate:null, periodEndDate:null, staleFundamentalsRejected:false, fundamentalsUnavailableReason:null };
  try { if(process.env.FMP_API_KEY){ const j=await fetchJson(`https://financialmodelingprep.com/api/v3/income-statement/${symbol}?limit=1&apikey=${process.env.FMP_API_KEY}`,{}).catch(()=>null) as unknown; const row=Array.isArray(j)?j[0] as Json:null; if(row && (num(row.revenue)!==null || num(row.netIncome)!==null)){ const fields=["revenue","netIncome","operatingIncome","totalAssets","totalLiabilities","cashAndCashEquivalents","operatingCashFlow","weightedAverageShsOut"].filter(k=>row[k]!=null); const filed=String(row.fillingDate ?? row.filedDate ?? row.date ?? ""); const fresh = daysOld(filed) <= FUNDAMENTALS_MAX_AGE_DAYS; return {...out, fundamentalsProofSource:"FMP", fundamentalsProofAvailable:fresh, fundamentalsProofFresh:fresh, fundamentalsProofFieldsUsed:fields, fundamentalsProofReceiptUrl:`https://financialmodelingprep.com/api/v3/income-statement/${symbol}?limit=1`, fundamentalsProofCompleteness: fresh ? (fields.length>=4?"good":"partial") : "historical_only", latestFiscalPeriod:row.period ?? null, formType:row.period ? "financial_statement" : null, filedDate:filed || null, periodEndDate:row.date ?? null, staleFundamentalsRejected:!fresh, fundamentalsUnavailableReason:fresh ? null : "latest_fundamentals_older_than_540_days_classified_as_historical_memory"}; }}
    const cik=await tickerToCik(symbol); if(!cik) return {...out, fundamentalsUnavailableReason:"ticker_to_cik_unavailable"}; const facts=await fetchJson(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`); const map: Record<string,string[]>={revenue:["Revenues","RevenueFromContractWithCustomerExcludingAssessedTax"],netIncome:["NetIncomeLoss"],operatingIncome:["OperatingIncomeLoss"],assets:["Assets"],liabilities:["Liabilities"],cash:["CashAndCashEquivalentsAtCarryingValue"],operatingCashFlow:["NetCashProvidedByUsedInOperatingActivities"],shares:["CommonStocksIncludingAdditionalPaidInCapital","EntityCommonStockSharesOutstanding"]}; const used: string[]=[]; let receipt: string | null=null; let latest: Json | null=null; for(const [field,names] of Object.entries(map)){ const row=latestFacts(facts,names); if(row){ used.push(field); latest=latest ?? row; receipt=`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`; }} if(!used.length) return {...out,fundamentalsUnavailableReason:"SEC companyfacts had no requested fresh 10-Q/10-K numeric fields"}; const fresh = daysOld(latest?.filed) <= FUNDAMENTALS_MAX_AGE_DAYS; return {...out,fundamentalsProofSource:"SEC companyfacts",fundamentalsProofAvailable:fresh,fundamentalsProofFresh:fresh,fundamentalsProofFieldsUsed:used,fundamentalsProofReceiptUrl:receipt,fundamentalsProofCompleteness:fresh ? (used.length>=4?"good":"partial") : "historical_only",latestFiscalPeriod:latest?.fp??null,formType:latest?.form??null,filedDate:latest?.filed??null,periodEndDate:latest?.end??null,staleFundamentalsRejected:!fresh,fundamentalsUnavailableReason:fresh ? null : "latest_companyfacts_10q_or_10k_older_than_540_days_classified_as_historical_memory"};
  } catch(e){ return {...out, fundamentalsUnavailableReason:e instanceof Error?e.message.slice(0,80):"fundamentals_failed_safe"}; }}
export async function recoverOfficialProof(t: string, signalType?: string) { const symbol=ticker(t); const signal=String(signalType ?? "").toLowerCase(); const base: Json={officialProofAvailable:false,officialProofRelevantToSignal:false,officialProofType:null,proofReclassifiedTo:null,officialProofSource:"SEC",officialProofUrl:null,accessionNumber:null,filingDate:null,formType:null,officialProofStrength:"none",officialProofMissingReason:null}; try{ const cik=await tickerToCik(symbol); if(!cik) return {...base,officialProofMissingReason:"ticker_to_cik_unavailable"}; const sub=await fetchJson(`https://data.sec.gov/submissions/CIK${cik}.json`); const recent=(sub.filings as Json)?.recent as Json; const forms=(recent?.form as string[])||[], acc=(recent?.accessionNumber as string[])||[], dates=(recent?.filingDate as string[])||[], docs=(recent?.primaryDocument as string[])||[]; for(let i=0;i<Math.min(forms.length,80);i++){ if(SEC_FORMS.has(String(forms[i]))){ const form=String(forms[i]); const isForm4=form==="4"; const form4Relevant=INSIDER_SIGNAL_TYPES.has(signal); const relevant=!isForm4 || form4Relevant; return {...base,officialProofAvailable:relevant,officialProofRelevantToSignal:relevant,officialProofType:relevant?form:null,proofReclassifiedTo:isForm4&&!form4Relevant?"insider_money_movement_context":null,officialProofUrl:filingUrl(cik,acc[i],docs[i]),accessionNumber:acc[i],filingDate:dates[i],formType:form,officialProofStrength:relevant ? (["8-K","10-Q","10-K","6-K"].includes(form)?"strong":(isForm4?"insider_context":"medium")) : "context_only",officialProofMissingReason:relevant?null:"form_4_is_insider_money_movement_context_not_broad_official_proof_for_this_signal"}; }} return {...base,officialProofMissingReason:"no_recent_relevant_sec_form_found"}; }catch(e){ return {...base,officialProofMissingReason:e instanceof Error?e.message.slice(0,80):"official_proof_failed_safe"}; }}
export async function recoverHistoricalMemory(c: Candidate) { const symbol=ticker(c.ticker); try{ const [events, raws, snaps]=process.env.DATABASE_URL?await Promise.all([prisma.historicalEvent.findMany({where:{ticker:symbol},take:5,orderBy:{eventDate:"desc"}}).catch(()=>[]),prisma.rawSignal.findMany({where:{ticker:symbol},take:10,orderBy:{receivedAt:"desc"}}).catch(()=>[]),prisma.priceSnapshot.findMany({where:{ticker:symbol},take:5,orderBy:{capturedAt:"desc"}}).catch(()=>[])]):[[],[],[]]; const similarStory=raws.some(r=>r.sourceUrl&&c.sourceUrl&&r.sourceUrl===c.sourceUrl)||raws.some(r=>r.title&&c.title&&crypto.createHash("sha1").update(r.title.toLowerCase()).digest("hex")===crypto.createHash("sha1").update(c.title.toLowerCase()).digest("hex")); const priorOutcomeReceipt=events.find(e=>Boolean(e.sourceUrl))?.sourceUrl??null; const priorPriceReactionAvailable=Boolean(events.some(e=>e.priceAfter1d||e.priceAfter7d)&&priorOutcomeReceipt)||snaps.length>1; const sameSourceOnlyRejected=Boolean(similarStory && events.length===0 && raws.length>0 && raws.every(r=>!r.sourceUrl || r.sourceUrl===c.sourceUrl)); const score=Math.min(90,events.length*20+raws.length*3+snaps.length*5); const historicalMemoryClean=Boolean(!sameSourceOnlyRejected && priorPriceReactionAvailable && score>=40); const available=historicalMemoryClean; return {historicalMemoryAvailable:available,historicalMemoryClean,historicalMemoryWeakReason:historicalMemoryClean?null:(!priorPriceReactionAvailable?"prior_price_reaction_needs_receipt_or_stored_outcome_reference":sameSourceOnlyRejected?"same_article_or_source_only_is_weak_context":score<40?"historical_confidence_below_40":"historical_memory_is_context_only"),priorOutcomeReceipt,sameSourceOnlyRejected,historicalMemorySourcesUsed:[events.length?"stored_historical_events":null,raws.length?"stored_raw_signals_or_article_hashes":null,snaps.length?"stored_price_snapshots":null].filter(Boolean),similarStorySeenBefore:similarStory,similarFilingSeenBefore:events.some(e=>/filing|sec|8-k|10-q|10-k/i.test(`${e.eventType} ${e.title??""}`)),priorPriceReactionAvailable,priorPatternType:events[0]?.eventType??null,historicalConfidenceScore:score,historicalMemoryReceiptRefs:[...events.map(e=>e.sourceUrl).filter(Boolean),...raws.map(r=>r.sourceUrl).filter(Boolean)].slice(0,5),historicalMemoryMissingReason:available?null:"no_clean_historical_memory_found"}; }catch(e){ return {historicalMemoryAvailable:false,historicalMemoryClean:false,historicalMemoryWeakReason:e instanceof Error?e.message.slice(0,80):"historical_memory_failed_safe",priorOutcomeReceipt:null,sameSourceOnlyRejected:false,historicalMemorySourcesUsed:[],similarStorySeenBefore:false,similarFilingSeenBefore:false,priorPriceReactionAvailable:false,priorPatternType:null,historicalConfidenceScore:0,historicalMemoryReceiptRefs:[],historicalMemoryMissingReason:e instanceof Error?e.message.slice(0,80):"historical_memory_failed_safe"}; }}
export async function recoverRiskProof(c: Candidate) { const text=`${c.title??""} ${c.summary??""}`.toLowerCase(); const hit=RISK.find(k=>text.includes(k)); if(hit) return {riskProofAvailable:true,riskProofType:"article_keyword",riskProofSource:c.sourceUrl?"existing_article":"existing_signal",riskProofUrl:c.sourceUrl??null,riskSeverity:["bankruptcy","fraud","default","subpoena","warning letter"].includes(hit)?"high":"medium",riskReason:`Matched risk keyword: ${hit}`,riskMissingReason:null}; const off=await recoverOfficialProof(c.ticker, c.signalType) as Json; if(String(off.formType).match(/S-1|S-3|424B/)) return {riskProofAvailable:true,riskProofType:"dilution_or_offering_filing",riskProofSource:"SEC",riskProofUrl:off.officialProofUrl,riskSeverity:"medium",riskReason:`Recent ${String(off.formType)} can indicate offering/dilution risk`,riskMissingReason:null}; return {riskProofAvailable:false,riskProofType:null,riskProofSource:null,riskProofUrl:null,riskSeverity:"none",riskReason:null,riskMissingReason:"no_risk_keyword_or_relevant_free_official_risk_source_found"}; }
export async function recoverPriceVolume(t: string) {
  const proof = await getPriceVolumeProofForTicker(t, { storeRaw: true }).catch((error) => ({
    ticker: ticker(t), priceVolumeProofAvailable: false, cleanPriceVolumeProof: false, latestPrice: null, latestPriceSource: null, latestPriceReceiptUrl: null, volume: null, volumeSource: null, averageVolume: null, volumeRatio: null, priceChange1d: null, priceChange5d: null, priceChange20d: null, relativeToSectorOrETF: null, marketReactionStatus: "unavailable", earlySignalPossible: true, proofCompleteness: "unavailable", sourceUsed: null, attemptedSources: [], failedSources: [{ source: "price_volume_router", reason: error instanceof Error ? error.message.slice(0, 80) : "failed_safe" }], unavailableReason: "price_volume_router_failed_safe", paidApiRequired: false, canFixWithoutPaidApi: true,
  }));
  return {
    ...proof,
    priceVolumeUnavailableReason: proof.unavailableReason,
    priceVolumeRecoveryDebug: {
      sourceUsed: proof.sourceUsed,
      attemptedSources: proof.attemptedSources,
      failedSources: proof.failedSources,
      finalUnavailableReason: proof.unavailableReason,
      paidApiRequired: proof.paidApiRequired,
      canFixWithoutPaidApi: proof.canFixWithoutPaidApi,
    },
    missingButNonBlockingFields: [!proof.averageVolume ? "averageVolume" : null, !proof.priceChange1d ? "priceChange1d" : null, !proof.priceChange5d ? "priceChange5d" : null, !proof.priceChange20d ? "priceChange20d" : null, proof.unavailableReason].filter(Boolean),
  };
}

async function candidates(max: number, provided?: unknown): Promise<Candidate[]> { if(Array.isArray(provided)) return provided.map(x=>x as Json).map(x=>({rawSignalId:String(x.rawSignalId??x.id??""),ticker:ticker(x.ticker),title:String(x.title??""),sourceUrl:String(x.sourceUrl??""),stage:String(x.stage??x.pipelineStage??"proof_needed"),proofTypes:Array.isArray(x.proofTypes)?x.proofTypes.map(String):[],missingProof:Array.isArray(x.missingProof)?x.missingProof.map(String):[],signalType:String(x.signalType??""),summary:String(x.summary??"")})).filter(c=>c.ticker).slice(0,max); if(!process.env.DATABASE_URL) return []; const rows=await prisma.rawSignal.findMany({where:{ticker:{not:null}},take:max,orderBy:{receivedAt:"desc"}}).catch(()=>[]); return rows.map(r=>({rawSignalId:r.id,ticker:ticker(r.ticker),title:r.title,sourceUrl:r.sourceUrl??undefined,stage:"proof_needed",proofTypes:[],missingProof:["fundamentals","official_proof","historical_memory","risk","price_volume"],signalType:r.signalType,summary:r.summary})).filter(c=>c.ticker); }

function asJson(value: unknown): Json { return value && typeof value === "object" && !Array.isArray(value) ? value as Json : {}; }
function strArray(value: unknown): string[] { return Array.isArray(value) ? value.map(String).filter(Boolean) : []; }
function countBy(items: string[]) { return items.reduce<Record<string, number>>((acc, item) => { acc[item] = (acc[item] ?? 0) + 1; return acc; }, {}); }
function qualityLabel(input: { proofType: string; proofSubType?: string | null; sourceName?: string | null; sourceUrl?: string | null; receiptUrl?: string | null; tickerMatch?: boolean; companyMatch?: boolean; relevantToSignal?: boolean; freshnessStatus?: string; cleanProof?: boolean; weakContextOnly?: boolean; rejectedReason?: string | null; }): Json {
  return {
    proofType: input.proofType,
    proofSubType: input.proofSubType ?? input.proofType,
    sourceName: input.sourceName ?? "unknown",
    sourceUrl: input.sourceUrl ?? input.receiptUrl ?? null,
    receiptUrl: input.receiptUrl ?? input.sourceUrl ?? null,
    tickerMatch: input.tickerMatch === true,
    companyMatch: input.companyMatch === true,
    relevantToSignal: input.relevantToSignal !== false,
    freshnessStatus: input.freshnessStatus ?? "unknown",
    cleanProof: input.cleanProof === true,
    weakContextOnly: input.weakContextOnly === true,
    rejectedReason: input.rejectedReason ?? null,
  };
}
function qualityItemsForRecovered(row: Json): Json[] {
  const c = asJson(row.candidate);
  const items: Json[] = [];
  const fundamentals = asJson(row.fundamentals);
  if (fundamentals.fundamentalsProofSource || fundamentals.fundamentalsUnavailableReason) items.push(qualityLabel({ proofType: "fundamentals", proofSubType: String(fundamentals.formType ?? "companyfacts_or_statement"), sourceName: String(fundamentals.fundamentalsProofSource ?? "SEC companyfacts"), receiptUrl: String(fundamentals.fundamentalsProofReceiptUrl ?? "") || null, tickerMatch: true, companyMatch: true, relevantToSignal: true, freshnessStatus: fundamentals.fundamentalsProofFresh ? "fresh" : fundamentals.staleFundamentalsRejected ? "stale_older_than_540_days" : "unknown", cleanProof: fundamentals.fundamentalsProofAvailable === true, weakContextOnly: fundamentals.staleFundamentalsRejected === true, rejectedReason: fundamentals.fundamentalsProofAvailable === true ? null : String(fundamentals.fundamentalsUnavailableReason ?? "fundamentals_unavailable_or_stale") }));
  const official = asJson(row.official);
  if (official.officialProofUrl || official.officialProofMissingReason) items.push(qualityLabel({ proofType: official.proofReclassifiedTo ? "insider/money_movement" : "official_proof", proofSubType: String(official.formType ?? official.officialProofType ?? "sec_filing"), sourceName: String(official.officialProofSource ?? "SEC"), receiptUrl: String(official.officialProofUrl ?? "") || null, tickerMatch: true, companyMatch: true, relevantToSignal: official.officialProofRelevantToSignal === true, freshnessStatus: "recent_submission", cleanProof: official.officialProofAvailable === true, weakContextOnly: official.proofReclassifiedTo === "insider_money_movement_context", rejectedReason: official.officialProofAvailable === true ? null : String(official.officialProofMissingReason ?? "no_relevant_official_proof") }));
  const historical = asJson(row.historical);
  if (historical.historicalMemorySourcesUsed || historical.historicalMemoryMissingReason) items.push(qualityLabel({ proofType: "historical_memory", proofSubType: historical.sameSourceOnlyRejected ? "same_article_or_source_memory" : "prior_outcome_memory", sourceName: "Swing Up historical memory", sourceUrl: String(c.sourceUrl ?? "") || null, receiptUrl: String(historical.priorOutcomeReceipt ?? "") || null, tickerMatch: true, companyMatch: false, relevantToSignal: historical.historicalMemoryClean === true, freshnessStatus: "historical_context", cleanProof: historical.historicalMemoryAvailable === true, weakContextOnly: historical.historicalMemoryAvailable !== true, rejectedReason: historical.historicalMemoryAvailable === true ? null : String(historical.historicalMemoryWeakReason ?? historical.historicalMemoryMissingReason ?? "historical_memory_weak_context_only") }));
  const risk = asJson(row.risk);
  if (risk.riskProofType || risk.riskMissingReason) items.push(qualityLabel({ proofType: "risk_legal_regulatory", proofSubType: String(risk.riskProofType ?? "risk_context"), sourceName: String(risk.riskProofSource ?? "risk_detector"), receiptUrl: String(risk.riskProofUrl ?? c.sourceUrl ?? "") || null, tickerMatch: true, companyMatch: false, relevantToSignal: risk.riskProofAvailable === true, freshnessStatus: "signal_context", cleanProof: risk.riskProofAvailable === true, weakContextOnly: risk.riskProofAvailable !== true, rejectedReason: risk.riskProofAvailable === true ? null : String(risk.riskMissingReason ?? "risk_source_not_applicable") }));
  const pv = asJson(row.priceVolume);
  if (pv.proofCompleteness || pv.priceVolumeUnavailableReason) items.push(qualityLabel({ proofType: "price_volume", proofSubType: String(pv.proofCompleteness ?? "quote"), sourceName: String(pv.latestPriceSource ?? "free_price_volume_adapter"), receiptUrl: String(pv.latestPriceSource ?? "") || null, tickerMatch: true, companyMatch: false, relevantToSignal: pv.latestPrice != null, freshnessStatus: pv.latestPrice != null ? "current_or_latest_available" : "unavailable", cleanProof: pv.latestPrice != null, weakContextOnly: pv.latestPrice == null, rejectedReason: pv.latestPrice != null ? null : String(pv.priceVolumeUnavailableReason ?? "latestPrice_null_rejected") }));
  return items;
}
function classifyBlocker(row: Json): string {
  const missing = strArray(row.stillMissingProof).join(" ");
  const f = asJson(row.fundamentals), o = asJson(row.official), h = asJson(row.historical), r = asJson(row.risk), pv = asJson(row.priceVolume);
  if (String(pv.priceVolumeUnavailableReason ?? "").includes("no_stored_snapshot")) return process.env.FMP_API_KEY || process.env.ALPHA_VANTAGE_API_KEY ? "missing_free_price_volume_adapter" : "missing_free_price_volume_adapter";
  if (f.staleFundamentalsRejected === true) return "stale_fundamentals_only";
  if (o.officialProofMissingReason || o.proofReclassifiedTo) return "no_relevant_official_proof";
  if (h.sameSourceOnlyRejected || String(h.historicalMemoryWeakReason ?? "").includes("same_article")) return "weak_historical_memory_only";
  if (r.riskMissingReason) return "risk_source_not_applicable";
  if (missing.includes("price_volume")) return "missing_paid_market_data";
  if (missing.includes("official")) return "no_relevant_official_proof";
  return strArray(row.proofAddedByFreeRecovery).length ? "proof_gate_correctly_blocked" : "candidate_low_impact";
}
export function buildProofVerificationReport(input: { includeFreeProofRecovery?: boolean; freeProofRecovery?: unknown; candidatesBeforeRecovery?: number; candidatesAfterRecovery?: number; topCandidates?: unknown[] } = {}): Json {
  const summary = asJson(input.freeProofRecovery);
  const rows = Array.isArray(summary.topRecoveredCandidates) ? summary.topRecoveredCandidates.map(asJson) : [];
  const allAdded = rows.flatMap((r) => strArray(r.proofAddedByFreeRecovery));
  const allQuality = rows.flatMap(qualityItemsForRecovered);
  const clean = allQuality.filter((p) => p.cleanProof === true).map((p) => String(p.proofType));
  const weak = allQuality.filter((p) => p.weakContextOnly === true || p.cleanProof !== true).map((p) => String(p.proofType));
  const stale = allQuality.filter((p) => String(p.freshnessStatus).includes("stale")).map((p) => String(p.proofType));
  const topCandidateDeltas = rows.map((r) => { const c = asJson(r.candidate); const before = strArray(r.beforeProofTypes); const after = strArray(r.afterProofTypes); const cleanAdded = qualityItemsForRecovered(r).filter((p) => p.cleanProof === true && !before.includes(String(p.proofType))).map((p) => String(p.proofType)); const weakRejected = qualityItemsForRecovered(r).filter((p) => p.cleanProof !== true).map((p) => String(p.proofType)); const stillMissing = strArray(r.stillMissingProof); return { rawSignalId: String(c.rawSignalId ?? ""), ticker: String(c.ticker ?? ""), title: String(c.title ?? ""), stageBefore: String(r.stageBeforeFreeRecovery ?? c.stage ?? "proof_needed"), stageAfter: String(r.stageAfterFreeRecovery ?? "proof_needed"), scoreBefore: c.score ?? c.promotionScore ?? null, scoreAfter: c.score ?? c.promotionScore ?? null, proofTypesBefore: before, proofTypesAfter: after, cleanProofTypesAdded: cleanAdded, weakProofTypesRejected: weakRejected, stillMissingRequiredProof: stillMissing.filter((x) => ["fundamentals","official_proof","price_volume"].includes(x)), stillMissingOptionalProof: stillMissing.filter((x) => !["fundamentals","official_proof","price_volume"].includes(x)), whyStillBlocked: stillMissing.length ? `Still missing clean proof: ${stillMissing.join(", ")}` : "Not blocked by free proof recovery report", nextBestProofToFetch: String(r.nextBestProofToFetch ?? "targeted official or price/volume proof"), canReachAiReviewAfterRecovery: after.filter((x) => !["raw_signal_source","source_health"].includes(x)).length >= 2 && stillMissing.length === 0, aiReviewBlockedReason: stillMissing.length ? `AI review locked until proof gate has clean required proof; missing ${stillMissing.join(", ")}` : null, attachedProofItems: qualityItemsForRecovered(r) }; });
  const blockers = rows.reduce<Record<string, { blockerType: string; count: number; exampleCandidate: unknown; recommendedFix: string; paidApiRequired: boolean; canFixNowWithoutPaidApi: boolean }>>((acc, row) => { const t = classifyBlocker(row); const c = asJson(row.candidate); acc[t] ??= { blockerType: t, count: 0, exampleCandidate: { ticker: c.ticker, title: c.title, rawSignalId: c.rawSignalId }, recommendedFix: t === "missing_paid_market_data" ? "Use existing free/stored price adapter first; paid market data may improve coverage but is not required for this build." : t === "missing_free_price_volume_adapter" ? "Add or repair a free/stored quote adapter that returns non-null latestPrice." : t === "stale_fundamentals_only" ? "Fetch fresher SEC companyfacts/FMP statement; keep old facts as historical context only." : t === "no_relevant_official_proof" ? "Fetch a signal-relevant SEC filing or official company/regulator receipt URL." : t === "weak_historical_memory_only" ? "Require independent historical outcome/price reaction, not the same article/source." : t === "risk_source_not_applicable" ? "Only attach risk proof when the signal is legal/regulatory/risk-related." : "Keep gate blocked until clean independent proof exists.", paidApiRequired: t === "missing_paid_market_data", canFixNowWithoutPaidApi: t !== "missing_paid_market_data" }; acc[t].count += 1; return acc; }, {});
  return redactSecrets({ freeProofRecoveryRan: input.includeFreeProofRecovery === true && summary.skipped !== true && summary.ok !== false, freeProofRecoverySkippedReason: input.includeFreeProofRecovery !== true ? "includeFreeProofRecovery=false" : summary.skipped === true ? String(summary.reason ?? "free_proof_recovery_skipped") : null, candidatesBeforeRecovery: input.candidatesBeforeRecovery ?? summary.candidatesInspected ?? rows.length, candidatesAfterRecovery: input.candidatesAfterRecovery ?? summary.candidatesInspected ?? rows.length, proofAddedByType: countBy(allAdded), cleanProofAddedByType: countBy(clean), weakProofRejectedByType: countBy(weak), staleProofRejectedByType: countBy(stale), form4ReclassifiedCount: rows.filter((r) => asJson(r.official).proofReclassifiedTo === "insider_money_movement_context").length, staleFundamentalsRejectedCount: rows.filter((r) => asJson(r.fundamentals).staleFundamentalsRejected === true).length, historicalMemoryWeakRejectedCount: rows.filter((r) => asJson(r.historical).historicalMemoryAvailable !== true).length, priceVolumeAttemptedCount: rows.filter((r) => r.priceVolume).length, priceVolumeAddedCount: rows.filter((r) => asJson(r.priceVolume).latestPrice != null).length, priceVolumeUnavailableReasons: countBy(rows.map((r) => String(asJson(r.priceVolume).priceVolumeUnavailableReason ?? "")).filter(Boolean)), candidatesMovedForwardCount: Number(summary.candidatesMovedForwardCount ?? rows.filter((r) => strArray(r.proofAddedByFreeRecovery).length).length), candidatesStillBlockedCount: Number(summary.candidatesStillBlockedCount ?? rows.filter((r) => strArray(r.stillMissingProof).length).length), topCandidateDeltas, candidateProofDelta: topCandidateDeltas, remainingGlobalBlockers: Object.values(blockers), nextBestBuildFix: Object.values(blockers).find((b) => b.canFixNowWithoutPaidApi)?.recommendedFix ?? "Add paid market data only after free/stored proof adapters are exhausted.", noOpenAI: true, noPublish: true, noTelegram: true, secretsRedacted: true });
}

export async function runFreeProofRecovery(input: Json={}) { const max=Math.max(1,Math.min(Number(input.maxCandidates??20),50)); const list=await candidates(max,input.candidates); const r2=input.includeR2TruthCheck===false?null:await getR2OperationalStatus().catch(e=>({errorCategory:"r2_truth_failed_safe",errorMessageSafe:e instanceof Error?e.message.slice(0,80):"r2_failed",secretsRedacted:true})); const recovered: Json[]=[]; for(const c of list){ const before=new Set(c.proofTypes??[]); const parts: Json={}; if(input.includeFundamentalsFallback!==false) parts.fundamentals=await recoverFundamentalsProof(c.ticker); if(input.includeOfficialProof!==false) parts.official=await recoverOfficialProof(c.ticker, c.signalType); if(input.includeHistoricalMemory!==false) parts.historical=await recoverHistoricalMemory(c); if(input.includeRiskDetector!==false) parts.risk=await recoverRiskProof(c); if(input.includeImprovedPriceVolume!==false) parts.priceVolume=await recoverPriceVolume(c.ticker); const added=[(parts.fundamentals as Json)?.fundamentalsProofAvailable?"fundamentals":null,(parts.official as Json)?.officialProofAvailable?"official_proof":null,(parts.historical as Json)?.historicalMemoryAvailable?"historical_memory":null,(parts.risk as Json)?.riskProofAvailable?"risk_legal_regulatory":null,(parts.priceVolume as Json)?.latestPrice?"price_volume":null].filter(Boolean) as string[]; const after=[...new Set([...before,...added])]; recovered.push({candidate:c,beforeProofTypes:[...before],afterProofTypes:after,proofAddedByFreeRecovery:added,stillMissingProof:["fundamentals","official_proof","historical_memory","risk_legal_regulatory","price_volume"].filter(x=>!after.includes(x)),nextBestProofToFetch:added.length?"review_next_missing_clean_proof":"SEC official filing or FMP quote if available",stageBeforeFreeRecovery:c.stage??"proof_needed",stageAfterFreeRecovery:after.length>before.size?"proof_needed_with_free_recovery":"proof_needed",...parts}); }
 const count=(k:string,field:string)=>recovered.filter(r=>Boolean(((r as Json)[k] as Json)?.[field])).length; return redactSecrets({ok:true,dryRun:input.dryRun!==false,candidatesInspected:list.length,r2TruthSummary:r2,fundamentalsProofAddedCount:count("fundamentals","fundamentalsProofAvailable"),officialProofAddedCount:count("official","officialProofAvailable"),historicalMemoryAddedCount:count("historical","historicalMemoryAvailable"),riskProofAddedCount:count("risk","riskProofAvailable"),improvedPriceVolumeAddedCount:recovered.filter(r=>Boolean((r["priceVolume"] as Json)?.latestPrice)).length,candidatesMovedForwardCount:recovered.filter(r=>Array.isArray(r.proofAddedByFreeRecovery) && r.proofAddedByFreeRecovery.length>0).length,candidatesStillBlockedCount:recovered.filter(r=>Array.isArray(r.stillMissingProof) && r.stillMissingProof.length>0).length,topRecoveredCandidates:recovered.slice(0,10),stillMissingProofSummary:recovered.flatMap(r=>Array.isArray(r.stillMissingProof)?r.stillMissingProof.map(String):[]).reduce<Record<string,number>>((a,x)=>{a[x]=(a[x]??0)+1;return a;},{}),nextBestFix:"Run targeted SEC/FMP/stored-data proof recovery for candidates still missing clean proof; no paid upgrade required.",proofQualityRuleVersion:"197D_stage1_proof_verification",attachedProofQualityLabels:recovered.flatMap(qualityItemsForRecovered),proofVerificationReport:buildProofVerificationReport({ includeFreeProofRecovery:true, freeProofRecovery:{ ok:true, candidatesInspected:list.length, topRecoveredCandidates:recovered, candidatesMovedForwardCount:recovered.filter(r=>Array.isArray(r.proofAddedByFreeRecovery) && r.proofAddedByFreeRecovery.length>0).length, candidatesStillBlockedCount:recovered.filter(r=>Array.isArray(r.stillMissingProof) && r.stillMissingProof.length>0).length } }),noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}); }
