import { checkR2Health } from "@/lib/r2-warehouse";

export type AssetType = "stock" | "etf" | "adr" | "international_stock" | "delisted_or_symbol_changed" | "crypto" | "fx" | "macro" | "fda_product_entity";
export type CostCategory = "free_bulk" | "cheap_bulk" | "medium_targeted" | "expensive_targeted" | "rate_limited_backup";
export type ProviderLimitRisk = "low" | "medium" | "high";

export const SOURCE_RELEVANCE_MAP = [
  { source: "FMP", usefulFor: ["stock", "etf", "adr", "international_stock"], roles: ["fundamentals", "price_volume", "earnings", "analyst_estimates", "price_targets", "transcripts", "press_releases", "financial_ratios"], hiddenMetrics: ["estimateRevisionScore", "fundamentalsChangeScore", "priceVolumeAnomalyScore", "catalystImpactScore"], wideScanUse: "bulk calendars, symbols, delisted/symbol-changed lists, light price snapshots", deepScanUse: "fundamentals, estimates, targets, transcripts, ratios, earnings surprise setup after a trigger", costCategory: "expensive_targeted", providerLimitRisk: "medium", rejectWhen: ["generic financial summary only", "no ticker/entity match"] },
  { source: "SEC EDGAR", usefulFor: ["stock", "adr", "delisted_or_symbol_changed"], roles: ["filings", "8-K events", "Form 4 insider trades", "13F"], hiddenMetrics: ["filingMaterialityScore", "insiderClusterScore", "regulatoryRiskScore"], wideScanUse: "recent submissions and company ticker maps", deepScanUse: "official filing proof, 8-K item classification, Form 4 cluster scoring, 13F context", costCategory: "cheap_bulk", providerLimitRisk: "medium", rejectWhen: ["non-public company with no CIK match"] },
  { source: "Marketaux", usefulFor: ["stock", "etf", "adr", "international_stock", "crypto"], roles: ["fresh company news", "entity/ticker sentiment"], hiddenMetrics: ["unusualMentionSpike", "sentimentShift", "sourceMentionSpikes"], wideScanUse: "wide discovery from provider entity metadata", deepScanUse: "direct company/entity catalyst confirmation only", costCategory: "medium_targeted", providerLimitRisk: "medium", rejectWhen: ["generic broad market article", "ticker-only comparison", "stale proof"] },
  { source: "Google News RSS", usefulFor: ["stock", "etf", "adr", "international_stock"], roles: ["targeted proof", "cross-source confirmation"], hiddenMetrics: ["proofDiversity", "proofMatchQuality", "sourceMentionSpikes"], wideScanUse: "not used for generic wide calls", deepScanUse: "company + ticker + catalyst topic searches", costCategory: "cheap_bulk", providerLimitRisk: "low", rejectWhen: ["generic query", "generic URL", "no catalyst topic"] },
  { source: "GDELT", usefulFor: ["stock", "etf", "international_stock", "fx", "macro"], roles: ["global event themes", "country risk", "sector/supply-chain themes"], hiddenMetrics: ["topicAcceleration", "macroRegimeFit", "supplyChainRippleScore"], wideScanUse: "global theme and event spike monitoring", deepScanUse: "company/topic matched geopolitical or supply-chain catalyst", costCategory: "cheap_bulk", providerLimitRisk: "low", rejectWhen: ["no specific company/topic/country-sector link"] },
  { source: "Alpha Vantage", usefulFor: ["stock", "etf", "fx", "crypto"], roles: ["backup news sentiment", "backup quote/fundamental sample"], hiddenMetrics: ["sentimentShift", "sourceReliabilityScore"], wideScanUse: "heavily budgeted backup only", deepScanUse: "small backup confirmation after stronger trigger", costCategory: "rate_limited_backup", providerLimitRisk: "high", rejectWhen: ["rate limit hit", "primary proof already sufficient"] },
  { source: "openFDA", usefulFor: ["fda_product_entity", "stock"], roles: ["healthcare/pharma/device regulation"], hiddenMetrics: ["regulatoryRiskScore", "catalystImpactScore"], wideScanUse: "drug/device/recall safety feeds", deepScanUse: "ticker-linked approval, recall, adverse-event spike", costCategory: "cheap_bulk", providerLimitRisk: "low", rejectWhen: ["no mapped healthcare product/company entity"] },
  { source: "FRED", usefulFor: ["macro", "stock", "etf", "fx"], roles: ["macro context"], hiddenMetrics: ["macroRegimeFit"], wideScanUse: "daily/periodic macro regime snapshots", deepScanUse: "sector-specific rate/inflation/liquidity context", costCategory: "free_bulk", providerLimitRisk: "low", rejectWhen: ["used as sole stock proof"] },
  { source: "Frankfurter FX", usefulFor: ["fx", "stock", "etf", "international_stock"], roles: ["FX context"], hiddenMetrics: ["macroRegimeFit"], wideScanUse: "currency pressure snapshots", deepScanUse: "exporter/importer exposure context", costCategory: "free_bulk", providerLimitRisk: "low", rejectWhen: ["no currency exposure link"] },
  { source: "CoinGecko", usefulFor: ["crypto", "stock", "etf"], roles: ["crypto beta", "risk appetite"], hiddenMetrics: ["macroRegimeFit", "sentimentShift"], wideScanUse: "crypto market risk snapshots", deepScanUse: "crypto-linked equities and ETFs only", costCategory: "cheap_bulk", providerLimitRisk: "medium", rejectWhen: ["no crypto linkage"] },
  { source: "FINRA", usefulFor: ["stock", "etf", "adr"], roles: ["short-sale pressure"], hiddenMetrics: ["shortPressureScore"], wideScanUse: "daily short-volume files", deepScanUse: "short-pressure context after shortlist", costCategory: "free_bulk", providerLimitRisk: "low", rejectWhen: ["not shortlisted"] },
  { source: "Wikidata", usefulFor: ["stock", "etf", "international_stock", "crypto"], roles: ["suppliers", "customers", "competitors"], hiddenMetrics: ["supplyChainRippleScore"], wideScanUse: "cached graph snapshots", deepScanUse: "ripple exposure after candidate shortlist", costCategory: "free_bulk", providerLimitRisk: "low", rejectWhen: ["weak or unmapped relationship"] },
] as const;

export const MEANINGFUL_METRIC_REGISTRY = [
  "directTickerMatch", "directCompanyMatch", "catalystImpactScore", "stockSpecificityScore", "sourceReliabilityScore", "proofMatchQuality", "proofDiversity", "unusualMentionSpike", "sentimentShift", "filingMaterialityScore", "insiderClusterScore", "estimateRevisionScore", "priceVolumeAnomalyScore", "fundamentalsChangeScore", "shortPressureScore", "supplyChainRippleScore", "regulatoryRiskScore", "historicalPatternScore", "macroRegimeFit", "earlySignalPossible", "marketReactionBonusOnly",
].map((name) => ({ name, required: true, marketReactionRequired: false, purpose: name === "marketReactionBonusOnly" ? "Price reaction can add confidence but never blocks early signals." : "Meaningful candidate scoring metric used to decide whether deeper calls are worth the cost." }));

const configured = (name: string) => Boolean(process.env[name]?.trim());

export function getGlobalUniverseStatus() {
  const sourceCoverageByAssetType: Record<string, string[]> = {};
  for (const source of SOURCE_RELEVANCE_MAP) for (const assetType of source.usefulFor) sourceCoverageByAssetType[assetType] = [...(sourceCoverageByAssetType[assetType] ?? []), source.source];
  const missingUniverseSources = [!configured("FMP_API_KEY") ? "FMP_API_KEY" : null, !configured("MARKETAUX_API_KEY") ? "MARKETAUX_API_KEY" : null, !configured("ALPHA_VANTAGE_API_KEY") ? "ALPHA_VANTAGE_API_KEY" : null, !configured("FRED_API_KEY") ? "FRED_API_KEY" : null].filter(Boolean);
  return { totalAssetsTracked: 0, stocksTracked: 0, etfsTracked: 0, cryptoAssetsTracked: 0, fxPairsTracked: 0, macroSeriesTracked: 0, companyEntityLinks: 0, tickerToCompanyMapCoverage: "planned_from_SEC_FMP_Marketaux_Wikidata_cached_maps", sourceCoverageByAssetType, lastUniverseSync: null, missingUniverseSources, nextRecommendedUniverseFix: "Run global universe sync into R2/PostgreSQL indexes; use SEC/FMP symbol maps first, then enrich entity links without exposing keys." };
}

export function buildGlobalSchedulerPlan(input: { maxAssetsToPlan?: number; maxAssetsToScanNow?: number; maxDeepScans?: number; respectProviderLimits?: boolean; confirmRun?: boolean; dryRun?: boolean; universeMode?: string; r2RawStorageReady?: boolean }) {
  const maxAssetsToPlan = Math.min(Math.max(input.maxAssetsToPlan ?? 1000, 1), 10000);
  const maxAssetsToScanNow = Math.min(Math.max(input.maxAssetsToScanNow ?? 50, 1), maxAssetsToPlan);
  const maxDeepScans = Math.min(Math.max(input.maxDeepScans ?? 5, 0), maxAssetsToScanNow);
  const sources = SOURCE_RELEVANCE_MAP.map((source) => source.source);
  const highValue = SOURCE_RELEVANCE_MAP.filter((source) => source.providerLimitRisk !== "high").slice(0, maxDeepScans).map((source) => ({ provider: source.source, reasonForCall: "direct ticker/entity catalyst plus proof gap", expectedSignalValue: "high", sourceRole: source.roles[0], tickerOrEntityTargeted: "candidate_shortlist_only", proofGapItMayFill: source.hiddenMetrics[0], costCategory: source.costCategory, providerLimitRisk: source.providerLimitRisk }));
  return { assetsConsidered: maxAssetsToPlan, sourcesConsidered: sources.length, sourcesConsideredPerAsset: "all relevant sources from sourceCoverageByAssetType are considered per ticker/entity", wideScansPlanned: maxAssetsToScanNow, deepScansPlanned: maxDeepScans, skippedDueToRateLimit: input.respectProviderLimits === false ? 0 : SOURCE_RELEVANCE_MAP.filter((source) => source.providerLimitRisk === "high").length, skippedDueToNoSourceRelevance: 0, highestValueNextCalls: highValue, expectedSignalValue: "quality_first_signal_value_per_call", expectedApiCost: input.confirmRun ? "bounded_by_plan" : "none_confirmRun_false", providerLimitRisk: input.respectProviderLimits === false ? "medium" : "low", storageMode: input.r2RawStorageReady ? "r2_raw_storage" : "postgresql_summary_only", r2RawStorageReady: Boolean(input.r2RawStorageReady), possibleSignals: [], unusualChanges: [], sourceMentionSpikes: [], newFilings: [], newCompanyNews: [], newEarningsEvents: [], newRegulatoryEvents: [], callPriorityRules: { high: "direct ticker + catalyst + proof gap", medium: "sector/theme spike", low: "generic broad article", reject: "unrelated topic, generic market commentary, stale proof" }, safety: { noOpenAIWhenConfirmRunFalse: input.confirmRun !== true, noPublish: true, noTelegram: true } };
}

export async function getSchedulerStatus() {
  const r2 = await checkR2Health(false);
  return { ok: true, universeMode: "global", everyTickerWatched: true, everyRelevantSourceConsidered: true, r2RawStorageReady: r2.canWrite === true && r2.canDelete === true, sourceCount: SOURCE_RELEVANCE_MAP.length, metricCount: MEANINGFUL_METRIC_REGISTRY.length, planDefaults: buildGlobalSchedulerPlan({ r2RawStorageReady: r2.canWrite === true && r2.canDelete === true }) };
}
