import crypto from "node:crypto";
import { getR2OperationalStatus, saveJsonToR2 } from "@/lib/r2-warehouse";
import { redactSecrets } from "@/lib/redact-secrets";

export type LiveSourceContract = {
  sourceId: string; displayName: string; area: string; sourceType: string; provider: string;
  requiresApiKey: boolean; apiKeyEnvName: string | null; baseUrl: string; exactQueryFormat: string;
  symbolFormat: string; acceptedSearchWords: string[]; requiredInputs: string[]; optionalInputs: string[];
  recommendedIntervalSeconds: number; maxItemsPerRun: number; maxCallsPerRun: number;
  dedupeKeyFields: string[]; rawStoragePathTemplate: string; proofTypesProduced: string[];
  riskLevel: "low" | "medium" | "high"; timeoutMs: number; backoffPolicy: string;
  enabledByDefault: boolean; failOpenOrFailClosed: "fail_open" | "fail_closed"; notes: string;
};

const rawPath = "raw/live-source-contract-tests/{sourceId}/{date}/{runId}.json";
const backoff = "exponential_backoff_with_jitter; do_not_retry_4xx_plan_or_auth_errors_in_same_run";
const fmpKey = "FMP_API_KEY";
const marketauxKey = "MARKETAUX_API_KEY";
function c(partial: Omit<LiveSourceContract, "rawStoragePathTemplate" | "timeoutMs" | "backoffPolicy" | "failOpenOrFailClosed"> & Partial<Pick<LiveSourceContract,"timeoutMs"|"backoffPolicy"|"failOpenOrFailClosed"|"rawStoragePathTemplate">>): LiveSourceContract {
  return { timeoutMs: 8000, backoffPolicy: backoff, failOpenOrFailClosed: "fail_open", rawStoragePathTemplate: rawPath, ...partial };
}
export const liveSourceContracts: LiveSourceContract[] = [
  c({ sourceId:"fmp_press_releases_latest", displayName:"FMP press releases latest", area:"company_live_announcements", sourceType:"provider_press_release_feed", provider:"FMP", requiresApiKey:true, apiKeyEnvName:fmpKey, baseUrl:"https://financialmodelingprep.com", exactQueryFormat:"/stable/news/press-releases-latest?page=0&limit=20", symbolFormat:"AAPL, MSFT, NVDA, AMD, GOOGL", acceptedSearchWords:["press release","announcement","product launch","guidance"], requiredInputs:[], optionalInputs:["page","limit"], recommendedIntervalSeconds:180, maxItemsPerRun:20, maxCallsPerRun:1, dedupeKeyFields:["url","publishedDate","symbol"], proofTypesProduced:["company_press_release"], riskLevel:"low", enabledByDefault:true, notes:"Latest company press releases; safe bulk discovery." }),
  c({ sourceId:"fmp_press_releases_by_symbol", displayName:"FMP press releases by symbol", area:"company_live_announcements", sourceType:"provider_symbol_press_releases", provider:"FMP", requiresApiKey:true, apiKeyEnvName:fmpKey, baseUrl:"https://financialmodelingprep.com", exactQueryFormat:"/stable/news/press-releases?symbols=AAPL", symbolFormat:"AAPL", acceptedSearchWords:["press release","guidance","contract","launch"], requiredInputs:["symbols"], optionalInputs:[], recommendedIntervalSeconds:180, maxItemsPerRun:20, maxCallsPerRun:4, dedupeKeyFields:["url","symbol","publishedDate"], proofTypesProduced:["company_press_release"], riskLevel:"low", enabledByDefault:true, notes:"Targeted press release proof after shortlist." }),
  c({ sourceId:"fmp_stock_news_latest", displayName:"FMP stock news latest", area:"company_live_announcements", sourceType:"provider_stock_news_feed", provider:"FMP", requiresApiKey:true, apiKeyEnvName:fmpKey, baseUrl:"https://financialmodelingprep.com", exactQueryFormat:"/stable/news/stock-latest?page=0&limit=20", symbolFormat:"AAPL, MSFT, NVDA, AMD, GOOGL", acceptedSearchWords:["stock news","earnings","guidance","lawsuit"], requiredInputs:[], optionalInputs:["page","limit"], recommendedIntervalSeconds:180, maxItemsPerRun:20, maxCallsPerRun:1, dedupeKeyFields:["url","symbol","publishedDate"], proofTypesProduced:["company_news"], riskLevel:"medium", enabledByDefault:true, notes:"News is discovery/context, not final official proof by itself. Also supports /stable/news/stock?symbols=AAPL." }),
  c({ sourceId:"marketaux_company_entity_news", displayName:"Marketaux company/entity news", area:"company_live_announcements", sourceType:"entity_news_api", provider:"Marketaux", requiresApiKey:true, apiKeyEnvName:marketauxKey, baseUrl:"https://api.marketaux.com", exactQueryFormat:"/v1/news/all?symbols=TSLA,AMZN,MSFT&filter_entities=true&language=en", symbolFormat:"TSLA,AMZN,MSFT", acceptedSearchWords:["product launch","guidance","FDA approval","contract award","lawsuit","investigation"], requiredInputs:["symbols or search"], optionalInputs:["filter_entities","language","must_have_entities"], recommendedIntervalSeconds:60, maxItemsPerRun:20, maxCallsPerRun:2, dedupeKeyFields:["uuid","url","entities.symbol"], proofTypesProduced:["company_news","entity_match"], riskLevel:"medium", enabledByDefault:true, notes:"Examples also include /v1/news/all?search=product launch&must_have_entities=true&language=en, /v1/news/similar/{uuid}, /v1/entity/stats/intraday?symbols=TSLA,AMZN,MSFT&interval=minute." }),
  c({ sourceId:"sec_company_filings_8k_6k", displayName:"SEC 8-K / 6-K company filings", area:"company_live_announcements", sourceType:"official_sec_company_submissions", provider:"SEC EDGAR", requiresApiKey:false, apiKeyEnvName:null, baseUrl:"https://data.sec.gov", exactQueryFormat:"/submissions/CIK##########.json", symbolFormat:"symbol must map to CIK first; CIK is 10 digits with leading zeros", acceptedSearchWords:["8-K","6-K","10-Q","10-K","Form 4","13D","13G","S-1","S-3","424B","DEF 14A"], requiredInputs:["CIK"], optionalInputs:["formTypes"], recommendedIntervalSeconds:60, maxItemsPerRun:40, maxCallsPerRun:4, dedupeKeyFields:["accessionNumber","form","filingDate","cik"], proofTypesProduced:["official_filing"], riskLevel:"low", enabledByDefault:true, notes:"Use polite SEC user-agent in production; classify 8-K, 6-K, 10-Q, 10-K, Form 4, 13D, 13G, S-1, S-3, 424B, DEF 14A." }),
  c({ sourceId:"company_ir_newsroom_allowlist", displayName:"Company IR/newsroom RSS/manual allowlist placeholder", area:"company_live_announcements", sourceType:"official_company_rss_allowlist_placeholder", provider:"Company official sites", requiresApiKey:false, apiKeyEnvName:null, baseUrl:"manual_allowlist://company-ir", exactQueryFormat:"allowlisted RSS/newsroom URL per company only", symbolFormat:"ticker plus verified official IR URL", acceptedSearchWords:["newsroom","investor relations","press release"], requiredInputs:["allowlistedOfficialUrl"], optionalInputs:["rssUrl"], recommendedIntervalSeconds:900, maxItemsPerRun:20, maxCallsPerRun:10, dedupeKeyFields:["officialUrl","publishedAt","title"], proofTypesProduced:["official_company_receipt"], riskLevel:"medium", enabledByDefault:false, notes:"Placeholder only until manual allowlist exists; no aggressive scraping." }),
];

const more: LiveSourceContract[] = [
  ["fmp_earnings_calendar","FMP earnings calendar","earnings_calls_transcripts","/stable/earnings-calendar",900,true,fmpKey,"earnings_calendar"], ["fmp_earnings_by_symbol","FMP earnings report by symbol","earnings_calls_transcripts","/stable/earnings?symbol=AAPL",900,true,fmpKey,"earnings_report"], ["fmp_transcript_latest","FMP earnings transcript latest","earnings_calls_transcripts","/stable/earning-call-transcript-latest",600,true,fmpKey,"transcript"], ["fmp_transcript_dates_by_symbol","FMP transcript dates by symbol","earnings_calls_transcripts","/stable/earning-call-transcript-dates?symbol=AAPL",600,true,fmpKey,"transcript_date"], ["fmp_transcript_by_symbol_year_quarter","FMP transcript by symbol/year/quarter","earnings_calls_transcripts","/stable/earning-call-transcript?symbol=AAPL&year=2024&quarter=4",600,true,fmpKey,"transcript"],
  ["benzinga_live_conference_call_transcripts","Benzinga live conference call transcripts placeholder","earnings_calls_transcripts","/api/v2.1/calendar/conference-calls/transcripts",600,true,"BENZINGA_API_KEY","transcript"], ["benzinga_conference_call_calendar","Benzinga conference call calendar placeholder","earnings_calls_transcripts","/api/v2.1/calendar/conference-calls",900,true,"BENZINGA_API_KEY","conference_call_calendar"],
  ["sec_latest_submissions","SEC latest filings / submissions","government_live_updates","/submissions/CIK##########.json",300,false,null,"official_filing"], ["sec_company_facts","SEC company facts","government_live_updates","/api/xbrl/companyfacts/CIK##########.json",3600,false,null,"company_facts"], ["openfda_enforcement_events","openFDA drug/device/food endpoints","government_live_updates","/drug/enforcement.json?search=product_description:aspirin",1800,false,null,"fda_public_data"], ["fda_press_release_feed","FDA press release/feed placeholder","government_live_updates","official FDA RSS/feed URL",900,false,null,"fda_press_release"], ["federal_reserve_rss","Federal Reserve RSS feeds","government_live_updates","RSS: all press releases, monetary policy, speeches, testimony, enforcement actions, selected interest rates, data announcements",180,false,null,"federal_reserve_release"], ["federal_register_search","Federal Register document search / public inspection","government_live_updates","/api/v1/documents.json?conditions%5Bterm%5D=product%20launch",1800,false,null,"federal_register_document"], ["congress_gov_placeholder","Congress.gov placeholder","government_live_updates","/v3/bill?query=semiconductor",3600,true,"CONGRESS_API_KEY","congress_document"], ["doj_press_release_placeholder","DOJ press release placeholder","government_live_updates","official DOJ press release feed/search",1800,false,null,"doj_release"], ["ftc_press_release_placeholder","FTC press release placeholder","government_live_updates","official FTC press release feed/search",1800,false,null,"ftc_release"],
  ["marketaux_product_topic_news","Marketaux product/topic news","product_launches","/v1/news/all?search=product launch&must_have_entities=true&language=en",180,true,marketauxKey,"product_news"], ["official_product_page_monitoring","Official product page monitoring placeholder","product_launches","official allowlisted product page URL",0,false,null,"official_product_page"], ["app_store_google_play_placeholder","App Store / Google Play / licensed app data placeholder","product_launches","licensed app data endpoint",0,true,"APP_DATA_API_KEY","app_listing"],
  ["fred_macro_snapshot","FRED macro snapshot","macro_announcements","/fred/series/observations?series_id=FEDFUNDS",86400,true,"FRED_API_KEY","macro_context"], ["bls_release_calendar_placeholder","BLS API/release-calendar placeholder","macro_announcements","scheduled release windows only",0,true,"BLS_API_KEY","macro_release"], ["bea_release_calendar_placeholder","BEA API/release-calendar placeholder","macro_announcements","scheduled release windows only",0,true,"BEA_API_KEY","macro_release"], ["treasury_releases_placeholder","Treasury releases placeholder","macro_announcements","official Treasury releases feed",1800,false,null,"treasury_release"], ["central_bank_rss_placeholder","central bank RSS placeholder","macro_announcements","official central bank RSS allowlist",1800,false,null,"central_bank_release"],
  ["courtlistener_api_placeholder","CourtListener API placeholder","court_legal_risk","/api/rest/v4/search/?q=company",86400,false,null,"court_record"], ["sec_enforcement_litigation_placeholder","SEC enforcement/litigation releases placeholder","court_legal_risk","official SEC litigation/enforcement feeds",3600,false,null,"sec_enforcement"], ["doj_enforcement_placeholder","DOJ enforcement placeholder","court_legal_risk","official DOJ enforcement feed/search",3600,false,null,"doj_enforcement"], ["ftc_enforcement_placeholder","FTC enforcement placeholder","court_legal_risk","official FTC enforcement feed/search",3600,false,null,"ftc_enforcement"], ["class_action_feed_placeholder","class action feed placeholder","court_legal_risk","licensed/allowlisted class action feed",86400,false,null,"class_action"],
  ["usaspending_awards","USAspending API","political_trade_contracts","/api/v2/search/spending_by_award/",86400,false,null,"contract_award"], ["sam_gov_opportunities","SAM.gov opportunities API","political_trade_contracts","/opportunities/v2/search?postedFrom=01/01/2026&postedTo=01/31/2026&limit=10",86400,true,"SAM_API_KEY","contract_opportunity"], ["quiver_api_placeholder","Quiver API placeholder","political_trade_contracts","licensed Quiver API endpoint",0,true,"QUIVER_API_KEY","political_trade"],
  ["social_fast_chatter_disabled","Social / fast chatter disabled placeholder","social_fast_chatter","disabled://social-sources",0,false,null,"disabled_chatter"],
].map(([sourceId, displayName, area, exactQueryFormat, interval, requiresApiKey, apiKeyEnvName, proof]) => c({ sourceId:String(sourceId), displayName:String(displayName), area:String(area), sourceType:String(displayName).toLowerCase().includes("placeholder") ? "safe_placeholder" : "official_or_licensed_api", provider:String(displayName).split(" ")[0], requiresApiKey:Boolean(requiresApiKey), apiKeyEnvName:apiKeyEnvName ? String(apiKeyEnvName) : null, baseUrl:String(exactQueryFormat).startsWith("/") ? "provider_base_url" : "official_or_licensed_source", exactQueryFormat:String(exactQueryFormat), symbolFormat:String(sourceId).includes("sec") ? "CIK########## after ticker-to-CIK mapping" : "AAPL, MSFT, NVDA, AMD, GOOGL or provider-specific documented format", acceptedSearchWords:["product launch","guidance","FDA approval","contract award","lawsuit","investigation"], requiredInputs:String(sourceId).includes("sam_gov") ? ["postedFrom","postedTo"] : [], optionalInputs:["symbols","keywords","limit","offset","title","ptype"], recommendedIntervalSeconds:Number(interval), maxItemsPerRun:20, maxCallsPerRun:Number(interval) === 0 ? 0 : 2, dedupeKeyFields:String(sourceId).includes("usaspending") ? ["award_id","recipient_name"] : ["url","id","publishedAt"], proofTypesProduced:[String(proof)], riskLevel:String(sourceId).includes("social") ? "high" : "medium", enabledByDefault: Number(interval) > 0 && (!String(sourceId).includes("benzinga") || Boolean(process.env.BENZINGA_API_KEY)) && !String(sourceId).includes("sam_gov"), notes: notesFor(String(sourceId)) }));
liveSourceContracts.push(...more);

function notesFor(id: string) { if (id.includes("social")) return "Disabled by default; do not scrape or call social sources because they are noisy and legal/quality sensitive."; if (id.includes("benzinga")) return "Contract exists but is enabled only when BENZINGA_API_KEY is present; do not call if missing."; if (id.includes("sam_gov")) return "Requires SAM_API_KEY and postedFrom/postedTo; disabled when key is missing."; if (id.includes("openfda")) return "Official FDA public data; do not use alone as final proof without company/ticker mapping."; if (id.includes("courtlistener")) return "Use safe API/search first; do not treat result as ticker proof unless entity match is strong."; return "V0 source contract; diagnostic only, no final alerts."; }
export function getLiveSourceContractSummary() { const missingApiKeys = Array.from(new Set(liveSourceContracts.filter((x)=>x.requiresApiKey && x.apiKeyEnvName && !process.env[x.apiKeyEnvName]).map((x)=>x.apiKeyEnvName as string))); const enabled = liveSourceContracts.filter(isContractEnabled); return { contractsLoadedCount: liveSourceContracts.length, enabledContractsCount: enabled.length, disabledContractsCount: liveSourceContracts.length - enabled.length, missingApiKeys, liveSourceNextBestAdditions:["Confirm R2 write/delete before storing raw receipts","Add ticker-to-CIK cache for SEC company contracts","Add official company IR allowlist","Enable SAM.gov only after SAM_API_KEY exists"] }; }
function isContractEnabled(x: LiveSourceContract) { if (!x.enabledByDefault) return false; if (x.requiresApiKey && x.apiKeyEnvName && !process.env[x.apiKeyEnvName]) return false; return true; }
export function buildLiveSourceSchedulerPlan() { return { ok:true, generatedAt:new Date().toISOString(), sources: liveSourceContracts.map((x)=>{ const missingKey = Boolean(x.requiresApiKey && x.apiKeyEnvName && !process.env[x.apiKeyEnvName]); const enabled = isContractEnabled(x); const intervalSeconds = x.recommendedIntervalSeconds; return { sourceId:x.sourceId, displayName:x.displayName, area:x.area, intervalSeconds, reason: intervalSeconds === 0 ? "Disabled/manual or scheduled-release mode only." : x.notes, maxCallsPerRun:x.maxCallsPerRun, dailyEstimatedCalls: enabled && intervalSeconds > 0 ? Math.ceil(86400 / intervalSeconds) * x.maxCallsPerRun : 0, priority: priority(x), enabled, disabled:!enabled, missingKey, riskNote:x.riskLevel + ": " + x.notes }; }), safetySummary:"Plan only; no automatic continuous pulling starts in this build." }; }
function priority(x: LiveSourceContract) { if (x.riskLevel === "low" && x.recommendedIntervalSeconds <= 300) return "high"; if (x.recommendedIntervalSeconds === 0) return "disabled"; return "normal"; }
function queryFor(x: LiveSourceContract, symbols:string[], keywords:string[]) { return x.exactQueryFormat.replace("AAPL", symbols[0] ?? "AAPL").replace("TSLA,AMZN,MSFT", symbols.slice(0,3).join(",") || "TSLA,AMZN,MSFT").replace("product launch", encodeURIComponent(keywords[0] ?? "product launch")); }
export async function runLiveSourceContractTest(input: Record<string, unknown>) { const dryRun = input.dryRun !== false; const confirmRun = input.confirmRun === true; const maxSources = Math.max(1, Math.min(Number(input.maxSources ?? 20), 50)); const symbols = Array.isArray(input.symbols) ? input.symbols.map(String) : ["NVDA","AMD","MSFT","GOOGL"]; const keywords = Array.isArray(input.keywords) ? input.keywords.map(String) : ["product launch","guidance"]; const runId = crypto.randomUUID(); const date = new Date().toISOString().slice(0,10); const summary = getLiveSourceContractSummary(); const results = liveSourceContracts.map((x)=>{ const apiKeyPresent = !x.requiresApiKey || Boolean(x.apiKeyEnvName && process.env[x.apiKeyEnvName]); const enabled = isContractEnabled(x); const skippedReason = !enabled ? (x.requiresApiKey && !apiKeyPresent ? `missing_${x.apiKeyEnvName}` : "disabled_by_contract") : (!confirmRun ? "dry_run_or_confirmRun_false_no_http_call" : null); return { sourceId:x.sourceId, displayName:x.displayName, area:x.area, enabled, skippedReason, apiKeyPresent, exactQueryBuilt: queryFor(x,symbols,keywords), symbolFormatUsed:x.symbolFormat, keywordFormatUsed:keywords.join(", "), httpStatus:null, resultCount:null, dedupeKeysCreated:x.dedupeKeyFields, rawStorageEligible: enabled && dryRun && !confirmRun, r2StorageAttempted:false, safeErrorCategory: skippedReason ? "not_called" : null, safeErrorMessage: skippedReason ? "Diagnostic built the contract query but did not call the source." : null, nextFix: skippedReason?.startsWith("missing_") ? `Add ${x.apiKeyEnvName} if this source should be enabled.` : x.notes }; }); const r2 = await getR2OperationalStatus().catch(()=>null); let r2StorageAttempted = false; if (r2?.writeAvailable) { r2StorageAttempted = true; await Promise.all(results.filter(r=>r.rawStorageEligible).slice(0,5).map((r)=>saveJsonToR2(`raw/live-source-contract-tests/${r.sourceId}/${date}/${runId}.json`, redactSecrets({ contractTest:r, runId, dryRun, confirmRun }), { source:"live-source-contract-test", sourceId:r.sourceId, dataType:"diagnostic_receipt", runId }).catch(()=>null))); }
  const plan = buildLiveSourceSchedulerPlan(); return { ok:true, runId, dryRun, confirmRun, ...summary, testedContracts: results.filter(r=>r.enabled).map(r=>r.sourceId), skippedContracts: results.filter(r=>r.skippedReason).map(r=>({sourceId:r.sourceId, reason:r.skippedReason})), sourceContractResults: results.map(r=>({...r, r2StorageAttempted: r2StorageAttempted && r.rawStorageEligible})), recommendedIntervals: Object.fromEntries(liveSourceContracts.map(x=>[x.sourceId,x.recommendedIntervalSeconds])), exactQueryExamples: Object.fromEntries(liveSourceContracts.map(x=>[x.sourceId,x.exactQueryFormat])), safetySummary:{ noOpenAiCall:true, noPublish:true, noTelegram:true, noSocialCalls:true, noPaywallBypass:true, noFakeSourceSuccess:true, r2WriteAvailable:Boolean(r2?.writeAvailable), r2RawReceiptStoredWhenAvailable:r2StorageAttempted, schedulerPlanAvailable:true }, schedulerPlan: plan.sources.slice(0,maxSources) };
}
