import crypto from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/client";
import { liveSourceContracts, type LiveSourceContract } from "@/lib/live-source-contracts";
import { getR2OperationalStatus, saveJsonToR2 } from "@/lib/r2-warehouse";
import { redactSecrets } from "@/lib/redact-secrets";

type JsonRecord = Record<string, unknown>;
type RawSignalCandidate = {
  sourceId: string; sourceName: string; sourceType: string; area: string; title: string; summary: string; url: string | null;
  publishedAt: string | null; receivedAt: string; symbols: string[]; companyNames: string[]; entities: string[]; keywordsMatched: string[];
  sourceReceiptUrl: string | null; storyHash: string; articleUrlHash: string | null; sourceReliabilityDefault: number; rawStorageRef: string | null;
  dedupeStatus: "new" | "duplicate" | "dry_run"; safeErrorCategory: string | null; externalId: string | null; raw: unknown;
};
export type LiveEarRunInput = { dryRun?: boolean; confirmRun?: boolean; maxSources?: number; maxItemsPerSource?: number; priorityMode?: string; symbols?: string[]; keywords?: string[]; maxCallsPerRun?: number; maxCallsPerMinute?: number; maxCallsPerDayEstimate?: number };
const state = globalThis as typeof globalThis & { __liveEarPulls?: Record<string, { lastAttemptAt?: string; lastSuccessfulPullAt?: string; backoffUntil?: string; callsToday?: number; day?: string; occurrence?: Record<string, number> }> };
state.__liveEarPulls ??= {};
const DAY = () => new Date().toISOString().slice(0, 10);
const hash = (v: string) => crypto.createHash("sha256").update(v.trim().toLowerCase()).digest("hex");
const safeText = (v: unknown) => typeof v === "string" ? v : v == null ? "" : String(v);
const arr = (v: unknown) => Array.isArray(v) ? v.map(String).filter(Boolean) : [];
function safeError(error: unknown) { const msg = error instanceof Error ? error.message : String(error); return { safeErrorCategory: /timeout/i.test(msg) ? "timeout" : /401|403|api key|auth/i.test(msg) ? "auth_or_plan" : /429|rate/i.test(msg) ? "rate_limited" : "source_failed", safeErrorMessage: redactSecrets(msg).slice(0, 180) }; }
function enabled(c: LiveSourceContract) { if (!c.enabledByDefault) return false; if (c.area === "social_fast_chatter") return false; if (c.sourceId.includes("placeholder")) return false; if (c.sourceId.includes("allowlist")) return false; if (c.requiresApiKey && c.apiKeyEnvName && !process.env[c.apiKeyEnvName]) return false; return true; }
function due(c: LiveSourceContract, mode: string) { const s = state.__liveEarPulls![c.sourceId] ?? {}; if (s.backoffUntil && Date.parse(s.backoffUntil) > Date.now()) return { ok:false, reason:"backoff_until_active" }; const interval = intervalFor(c, mode); if (s.lastSuccessfulPullAt && Date.now() - Date.parse(s.lastSuccessfulPullAt) < interval * 1000) return { ok:false, reason:`interval_not_due_${interval}s` }; return { ok:true, reason:null }; }
function intervalFor(c: LiveSourceContract, mode: string) { const base = c.recommendedIntervalSeconds || 3600; if (mode === "aggressive" && c.riskLevel === "low") return Math.max(30, Math.floor(base / 2)); if (mode === "conservative") return Math.min(86400, base * 2); return base; }
function urlFor(c: LiveSourceContract, symbols: string[], keywords: string[], maxItems: number) { const fmp = `apikey=${encodeURIComponent(process.env.FMP_API_KEY ?? "")}`; const marketaux = `api_token=${encodeURIComponent(process.env.MARKETAUX_API_KEY ?? "")}`; const benz = `token=${encodeURIComponent(process.env.BENZINGA_API_KEY ?? "")}`; switch (c.sourceId) {
  case "fmp_press_releases_latest": return `https://financialmodelingprep.com/stable/news/press-releases-latest?page=0&limit=${maxItems}&${fmp}`;
  case "fmp_press_releases_by_symbol": return `https://financialmodelingprep.com/stable/news/press-releases?symbols=${symbols.join(",")}&limit=${maxItems}&${fmp}`;
  case "fmp_stock_news_latest": return `https://financialmodelingprep.com/stable/news/stock-latest?page=0&limit=${maxItems}&${fmp}`;
  case "fmp_earnings_calendar": return `https://financialmodelingprep.com/stable/earnings-calendar?limit=${maxItems}&${fmp}`;
  case "fmp_transcript_latest": return `https://financialmodelingprep.com/stable/earning-call-transcript-latest?limit=${maxItems}&${fmp}`;
  case "fmp_transcript_dates_by_symbol": return `https://financialmodelingprep.com/stable/earning-call-transcript-dates?symbol=${symbols[0] ?? "NVDA"}&${fmp}`;
  case "marketaux_company_entity_news": return `https://api.marketaux.com/v1/news/all?symbols=${symbols.join(",")}&filter_entities=true&must_have_entities=true&language=en&limit=${maxItems}&${marketaux}`;
  case "marketaux_product_topic_news": return `https://api.marketaux.com/v1/news/all?search=${encodeURIComponent(keywords[0] ?? "product launch")}&must_have_entities=true&language=en&limit=${maxItems}&${marketaux}`;
  case "openfda_enforcement_events": return `https://api.fda.gov/drug/enforcement.json?limit=${Math.min(maxItems, 10)}`;
  case "federal_register_search": return `https://www.federalregister.gov/api/v1/documents.json?per_page=${maxItems}&conditions%5Bterm%5D=${encodeURIComponent(keywords[0] ?? "investigation")}`;
  case "federal_reserve_rss": return "https://www.federalreserve.gov/feeds/press_all.xml";
  case "fred_macro_snapshot": return `https://api.stlouisfed.org/fred/series/observations?series_id=FEDFUNDS&file_type=json&limit=1&api_key=${encodeURIComponent(process.env.FRED_API_KEY ?? "")}`;
  case "usaspending_awards": return "https://api.usaspending.gov/api/v2/search/spending_by_award/";
  case "sam_gov_opportunities": return `https://api.sam.gov/opportunities/v2/search?limit=${maxItems}&api_key=${encodeURIComponent(process.env.SAM_API_KEY ?? "")}`;
  case "benzinga_live_conference_call_transcripts": return `https://api.benzinga.com/api/v2.1/calendar/conference-calls/transcripts?${benz}`;
  case "benzinga_conference_call_calendar": return `https://api.benzinga.com/api/v2.1/calendar/conference-calls?${benz}`;
  default: return null;
} }
function parseItems(c: LiveSourceContract, data: unknown, receivedAt: string, symbols: string[], keywords: string[]): RawSignalCandidate[] { const root = data as JsonRecord; const rows = Array.isArray(data) ? data : Array.isArray(root.data) ? root.data : Array.isArray(root.results) ? root.results : Array.isArray(root.awards) ? root.awards : Array.isArray(root.observations) ? root.observations : [];
 return rows.map((item: unknown) => { const r = item as JsonRecord; const title = safeText(r.title || r.headline || r.name || r.award_description || r.product_description || r.event || c.displayName).slice(0, 240); const url = safeText(r.url || r.link || r.final_url || r.html_url || r.document_url) || null; const publishedAt = safeText(r.publishedDate || r.published_at || r.date || r.filingDate || r.publication_date || r.action_date) || null; const sym = arr(r.symbols).concat(safeText(r.symbol || r.ticker).split(",")).map(s=>s.trim().toUpperCase()).filter(Boolean); const textBlob = `${title} ${safeText(r.summary || r.text || r.description)}`.toLowerCase(); const matched = keywords.filter(k => textBlob.includes(k.toLowerCase())); const externalId = safeText(r.id || r.uuid || r.accessionNumber || r.award_id) || null; const storyHash = hash([c.sourceId, title, publishedAt, sym.join(","), externalId].join("|")); return { rawSignalId: crypto.randomUUID(), sourceId:c.sourceId, sourceName:c.displayName, sourceType:c.sourceType, area:c.area, title, summary:safeText(r.summary || r.text || r.description || r.abstract).slice(0, 600), url, publishedAt, receivedAt, symbols:[...new Set(sym.length ? sym : symbols.filter(s => textBlob.includes(s.toLowerCase())))], companyNames:[], entities:[], keywordsMatched:matched, sourceReceiptUrl:url, storyHash, articleUrlHash:url ? hash(url) : null, sourceReliabilityDefault:c.riskLevel === "low" ? 85 : 65, rawStorageRef:null, dedupeStatus:"new", safeErrorCategory:null, externalId, raw:item }; }); }
async function fetchSource(c: LiveSourceContract, url: string, maxItems: number, symbols: string[], keywords: string[]) { const init: RequestInit = { cache:"no-store", headers: { "user-agent":"SwingUpLiveEars/1.0 contact=ops@swingup.local", accept: url.endsWith(".xml") ? "application/rss+xml,text/xml" : "application/json" } }; if (c.sourceId === "usaspending_awards") { init.method = "POST"; init.headers = { ...init.headers, "content-type":"application/json" }; init.body = JSON.stringify({ limit:maxItems, page:1, filters:{ keywords }, fields:["Award ID","Recipient Name","Award Description","Start Date","generated_internal_id"] }); } const res = await fetch(url, init); const httpStatus = res.status; if (!res.ok) throw new Error(`source_http_${httpStatus}`); const text = await res.text(); if (url.endsWith(".xml")) {
    const xmlItems = [...text.matchAll(/<item>[\s\S]*?<title>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?<\/title>[\s\S]*?<link>(.*?)<\/link>/g)]
      .slice(0, maxItems)
      .map((m) => ({ title: m[1]?.replace(/<[^>]+>/g, "").trim(), url: m[2]?.trim() }));
    return { httpStatus, items: parseItems(c, xmlItems, new Date().toISOString(), symbols, keywords).slice(0, maxItems) };
  }
  return { httpStatus, items: parseItems(c, JSON.parse(text || "{}"), new Date().toISOString(), symbols, keywords).slice(0, maxItems) }; }
async function persist(candidate: RawSignalCandidate, dryRun: boolean, rawStorageRef: string | null) { candidate.rawStorageRef = rawStorageRef; const existing = process.env.DATABASE_URL ? await prisma.rawSignal.findFirst({ where: { OR: [{ sourceUrl: candidate.url ?? undefined }, { source: candidate.sourceName, title: candidate.title }] } }) : null; if (existing) { const payload = { ...(existing.payload as JsonRecord), liveEarDedupe: { lastSeenAt: candidate.receivedAt, occurrenceCount: Number(((existing.payload as JsonRecord)?.liveEarDedupe as JsonRecord)?.occurrenceCount ?? 1) + 1, storyHash: candidate.storyHash } }; if (!dryRun) await prisma.rawSignal.update({ where:{ id: existing.id }, data:{ payload: payload as Prisma.InputJsonValue } }); return "duplicate" as const; }
 if (!dryRun && process.env.DATABASE_URL) await prisma.rawSignal.create({ data:{ source:candidate.sourceName, ticker:candidate.symbols[0] ?? null, signalType:candidate.area, title:candidate.title || "Untitled live ear signal", summary:candidate.summary, sourceUrl:candidate.url, importanceHint:candidate.sourceReliabilityDefault >= 80 ? "high" : "medium", payload: redactSecrets(candidate) as Prisma.InputJsonValue } }); return dryRun ? "dry_run" as const : "new" as const; }
export async function runLiveEarRun(input: LiveEarRunInput) { const dryRun = input.dryRun !== false; const runId = crypto.randomUUID(); const symbols = (input.symbols?.length ? input.symbols : ["NVDA","AMD","MSFT","GOOGL"]).map(s=>s.toUpperCase()); const keywords = input.keywords?.length ? input.keywords : ["product launch","guidance","FDA approval","contract award","lawsuit","investigation","revenue","partnership"]; const maxItems = Math.min(Math.max(Number(input.maxItemsPerSource ?? 20),1),50); const maxSources = Math.min(Math.max(Number(input.maxSources ?? 20),1),50); const maxCalls = Math.min(Math.max(Number(input.maxCallsPerRun ?? 20),1),100); const mode = input.priorityMode ?? "balanced"; const missingApiKeys = [...new Set(liveSourceContracts.filter(c=>c.requiresApiKey && c.apiKeyEnvName && !process.env[c.apiKeyEnvName]).map(c=>c.apiKeyEnvName!))]; const selected = liveSourceContracts.filter(enabled).slice(0, maxSources); const r2 = await getR2OperationalStatus().catch(()=>null); let calls = 0, newRawSignalsCreated = 0, duplicatesSkipped = 0, duplicatesUpdated = 0, rawStoredInR2Count = 0; const sourceResults: JsonRecord[] = [], bestNewSignals: JsonRecord[] = [], failuresBySource: JsonRecord[] = [], skipped: JsonRecord[] = [];
 for (const c of liveSourceContracts) { if (selected.includes(c)) continue; const reason = c.area === "social_fast_chatter" ? "noisy_legal_quality_sensitive" : c.requiresApiKey && c.apiKeyEnvName && !process.env[c.apiKeyEnvName] ? `missing_${c.apiKeyEnvName}` : !c.enabledByDefault || c.sourceId.includes("placeholder") || c.sourceId.includes("allowlist") ? "disabled_until_safe_adapter_exists" : "max_sources_or_interval_policy"; if (!enabled(c) || skipped.length < maxSources) skipped.push({ sourceId:c.sourceId, area:c.area, reason }); }
 for (const c of selected) { const pull = due(c, mode); const url = urlFor(c, symbols, keywords, maxItems); if (!pull.ok || !url || calls >= maxCalls) { const skippedReason = calls >= maxCalls ? "run_budget_exhausted" : (!url ? "adapter_not_active_yet" : pull.reason); sourceResults.push({ sourceId:c.sourceId, area:c.area, attempted:false, skippedReason, httpStatus:null, itemCount:0, newSignals:0, duplicates:0, r2Stored:0, safeErrorCategory:null, safeErrorMessage:null }); continue; }
  const st = state.__liveEarPulls![c.sourceId] ??= {}; st.lastAttemptAt = new Date().toISOString(); calls++;
  try { const got = await fetchSource(c, url, maxItems, symbols, keywords); let newCount=0, dupCount=0, r2Count=0; for (const cand of got.items as RawSignalCandidate[]) { const r2Key = r2?.writeAvailable ? `raw/live-ears/${c.sourceId}/${DAY()}/${runId}/${cand.storyHash}.json` : null; let ref: string | null = null; if (r2Key) { ref = await saveJsonToR2(r2Key, redactSecrets(cand), { source:c.sourceId, sourceId:c.sourceId, dataType:"live-ear-raw", runId }).then(x=>x?.r2Key ?? r2Key).catch(()=>null); if (ref) { rawStoredInR2Count++; r2Count++; } } const status = await persist(cand, dryRun, ref); if (status === "duplicate") { dupCount++; duplicatesSkipped++; duplicatesUpdated += dryRun ? 0 : 1; } else { newCount++; if (!dryRun) newRawSignalsCreated++; bestNewSignals.push({ title:cand.title, sourceId:c.sourceId, url:cand.url, symbols:cand.symbols, storyHash:cand.storyHash }); } }
   st.lastSuccessfulPullAt = new Date().toISOString(); sourceResults.push({ sourceId:c.sourceId, area:c.area, attempted:true, skippedReason:null, httpStatus:got.httpStatus, itemCount:(got.items as unknown[]).length, newSignals:newCount, duplicates:dupCount, r2Stored:r2Count, safeErrorCategory:null, safeErrorMessage:null });
  } catch(e) { const se = safeError(e); st.backoffUntil = new Date(Date.now() + 5*60*1000).toISOString(); failuresBySource.push({ sourceId:c.sourceId, ...se }); sourceResults.push({ sourceId:c.sourceId, area:c.area, attempted:true, skippedReason:null, httpStatus:null, itemCount:0, newSignals:0, duplicates:0, r2Stored:0, ...se }); }
 }
 return { ok:true, dryRun, confirmRun: input.confirmRun === true, runId, sourcesAttempted: sourceResults.filter(r=>r.attempted).length, sourcesSkipped: skipped, missingApiKeys, maxCallsPerRun:maxCalls, maxCallsPerMinute: input.maxCallsPerMinute ?? 20, maxCallsPerDayEstimate: input.maxCallsPerDayEstimate ?? 1000, callsUsedThisRun:calls, callsSkippedDueToBudget: sourceResults.filter(r=>r.skippedReason === "run_budget_exhausted").length, backoffReason:"per_source_backoff_on_safe_failure", newRawSignalsCreated, duplicatesSkipped, duplicatesUpdated, storyHashesCreated: dryRun ? bestNewSignals.length : newRawSignalsCreated, rawStoredInR2Count, sourceResults, bestNewSignals: bestNewSignals.slice(0,10), failuresBySource, nextRecommendedSourceFix: missingApiKeys[0] ? `Add ${missingApiKeys[0]} when ready, or leave skipped safely.` : failuresBySource[0]?.sourceId ? `Review safe adapter/error for ${failuresBySource[0].sourceId}.` : "Add ticker-to-CIK mapping for SEC company filing ears.", noOpenAI:true, noPublish:true, noTelegram:true, secretsRedacted:true };
}
