import crypto from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/client";
import { getR2OperationalStatus, saveJsonToR2 } from "@/lib/r2-warehouse";
import { redactSecrets } from "@/lib/redact-secrets";

type Json = Record<string, unknown>;
export type OfficialAnnouncementInput = { dryRun?: boolean; confirmRun?: boolean; symbols?: string[]; companyNames?: string[]; keywords?: string[]; maxItemsPerSource?: number; timeoutMs?: number; clusters?: Json[] };
const DAY=()=>new Date().toISOString().slice(0,10);
const h=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex");
const txt=(v:unknown)=>typeof v==="string"?v:v==null?"":String(v);
const arr=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const clean=(s:string)=>s.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const ua={"user-agent":"SwingUpOfficialAnnouncements/1.0 contact=support@swingup.app",accept:"application/json, application/rss+xml, application/xml, text/xml"};
async function get(url:string, timeoutMs:number){ const ac=new AbortController(); const t=setTimeout(()=>ac.abort(),timeoutMs); try{ const r=await fetch(url,{cache:"no-store",signal:ac.signal,headers:ua}); const body=await r.text(); if(!r.ok) throw new Error(`http_${r.status}`); return body; } finally{ clearTimeout(t); }}
async function json(url:string, timeoutMs:number){ return JSON.parse(await get(url,timeoutMs)||"{}"); }
function confidence(blob:string,symbol:string,company:string){ const b=blob.toLowerCase(); let score=0; if(symbol&&new RegExp(`\\b${symbol.toLowerCase()}\\b`).test(b)) score+=45; if(company&&b.includes(company.toLowerCase())) score+=55; return Math.min(100,score); }
function signal(p:{sourceName:string;sourceType:string;title:string;summary?:string;officialUrl:string;publishedAt?:string|null;ticker?:string|null;company?:string|null;officialProofType:string;officialProofStrength:"strong"|"contract"|"placeholder";accessionOrDocumentId?:string|null;raw?:unknown;receivedAt:string;rawStorageRef?:string|null}){ const storyHash=h([p.ticker,p.company,p.officialProofType,p.title,(p.publishedAt||"").slice(0,10)].join("|")); const entityMatchConfidence=confidence(`${p.title} ${p.summary} ${JSON.stringify(p.raw).slice(0,800)}`,p.ticker||"",p.company||""); return { sourceName:p.sourceName, officialSource:true, sourceType:p.sourceType, title:p.title.slice(0,240), summary:clean(p.summary||"").slice(0,900), officialUrl:p.officialUrl, publishedAt:p.publishedAt||null, receivedAt:p.receivedAt, ticker:p.ticker||null, company:p.company||null, entityMatchConfidence, officialProofType:p.officialProofType, officialProofStrength:p.officialProofStrength, accessionOrDocumentId:p.accessionOrDocumentId||null, storyHash, rawStorageRef:p.rawStorageRef||null, raw:redactSecrets(p.raw??{})}; }
const FORMS=new Set(["8-K","6-K","10-Q","10-K","4","13D","13G","S-1","S-3","424B","DEF 14A"]);
async function sec(symbols:string[], companies:string[], max:number, timeoutMs:number, receivedAt:string){ const out:ReturnType<typeof signal>[]=[]; const map=await json("https://www.sec.gov/files/company_tickers.json",timeoutMs).catch(()=>({} as Json)); for(const sym of symbols){ const entry=Object.values(map as Json).find((e)=>txt((e as Json).ticker).toUpperCase()===sym) as Json|undefined; if(!entry) continue; const cik=String(entry.cik_str).padStart(10,"0"); const sub=await json(`https://data.sec.gov/submissions/CIK${cik}.json`,timeoutMs).catch(()=>null) as Json|null; const rec=(sub?.filings as Json|undefined)?.recent as Json|undefined; const forms=arr(rec?.form), acc=arr(rec?.accessionNumber), dates=arr(rec?.filingDate), docs=arr(rec?.primaryDocument); for(let i=0;i<forms.length&&out.length<max;i++){ const form=forms[i]; if(!FORMS.has(form)&&![...FORMS].some(f=>form.startsWith(f))) continue; const accession=acc[i]; const nodash=accession.replace(/-/g,""); const doc=docs[i]||`${accession}-index.html`; const url=`https://www.sec.gov/Archives/edgar/data/${Number(entry.cik_str)}/${nodash}/${doc}`; out.push(signal({sourceName:"SEC EDGAR",sourceType:"sec_filing",title:`${sym} ${form} filing`,summary:`Official SEC ${form} filing for ${txt(sub?.name)||companies[symbols.indexOf(sym)]||sym}.`,officialUrl:url,publishedAt:dates[i],ticker:sym,company:txt(sub?.name)||companies[symbols.indexOf(sym)]||null,officialProofType:"sec_filing",officialProofStrength:"strong",accessionOrDocumentId:accession,raw:{cik,form,accession,filingDate:dates[i],primaryDocument:doc},receivedAt})); } } return out; }
function rssItems(xml:string){ return [...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].map(m=>m[0]).map(x=>({title:clean(txt(x.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1])), link:clean(txt(x.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1])), pubDate:clean(txt(x.match(/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i)?.[1])), description:clean(txt(x.match(/<description[^>]*>([\s\S]*?)<\/description>/i)?.[1]))})); }
async function feed(name:string,type:string,url:string,proofType:string,keywords:string[],symbols:string[],companies:string[],max:number,timeoutMs:number,receivedAt:string){ const xml=await get(url,timeoutMs); return rssItems(xml).filter(i=>keywords.concat(symbols,companies).some(k=>`${i.title} ${i.description}`.toLowerCase().includes(k.toLowerCase()))).slice(0,max).map(i=>{ const ix=companies.findIndex(c=>`${i.title} ${i.description}`.toLowerCase().includes(c.toLowerCase())); return signal({sourceName:name,sourceType:type,title:i.title||name,summary:i.description,officialUrl:i.link||url,publishedAt:i.pubDate?new Date(i.pubDate).toISOString():null,ticker:ix>=0?symbols[ix]:null,company:ix>=0?companies[ix]:null,officialProofType:proofType,officialProofStrength:"strong",accessionOrDocumentId:i.link?h(i.link).slice(0,24):null,raw:i,receivedAt}); }); }
const COMPANY_FEEDS:{ticker:string;company:string;url:string}[]=[
 {ticker:"NVDA",company:"NVIDIA",url:"https://nvidianews.nvidia.com/news?pagetemplate=rss"},
 {ticker:"AMD",company:"Advanced Micro Devices",url:"https://ir.amd.com/news-events/press-releases/rss"},
 {ticker:"MSFT",company:"Microsoft",url:"https://news.microsoft.com/feed/"},
 {ticker:"GOOGL",company:"Alphabet",url:"https://abc.xyz/investor/news/rss/"},
];
async function federalRegister(keywords:string[],symbols:string[],companies:string[],max:number,timeoutMs:number,receivedAt:string){ const q=encodeURIComponent(keywords.concat(companies).slice(0,12).join(" ")); const data=await json(`https://www.federalregister.gov/api/v1/documents.json?per_page=${max}&order=newest&conditions%5Bterm%5D=${q}`,timeoutMs).catch(()=>({results:[]})) as Json; return ((data.results as Json[]|undefined)||[]).map(d=>signal({sourceName:"Federal Register",sourceType:"federal_register",title:txt(d.title)||"Federal Register document",summary:txt(d.abstract),officialUrl:txt(d.html_url)||txt(d.pdf_url),publishedAt:txt(d.publication_date),ticker:null,company:companies.find(c=>`${d.title} ${d.abstract}`.toLowerCase().includes(c.toLowerCase()))||null,officialProofType:"federal_register_document",officialProofStrength:"strong",accessionOrDocumentId:txt(d.document_number),raw:d,receivedAt})); }
async function usaSpending(companies:string[],symbols:string[],max:number,timeoutMs:number,receivedAt:string){ const rows:ReturnType<typeof signal>[]=[]; for(let i=0;i<companies.length;i++){ const body={filters:{recipient_search_text:[companies[i]],time_period:[{start_date:new Date(Date.now()-30*864e5).toISOString().slice(0,10),end_date:DAY()}]},fields:["Award ID","Recipient Name","Award Amount","Start Date","Awarding Agency","Description"],page:1,limit:max,sort:"Start Date",order:"desc"}; const ac=new AbortController(); const t=setTimeout(()=>ac.abort(),timeoutMs); try{ const r=await fetch("https://api.usaspending.gov/api/v2/search/spending_by_award/",{method:"POST",headers:{...ua,"content-type":"application/json"},body:JSON.stringify(body),signal:ac.signal,cache:"no-store"}); const j=await r.json() as Json; for(const d of ((j.results as Json[])||[])) rows.push(signal({sourceName:"USAspending",sourceType:"official_contract_award",title:`${txt(d["Recipient Name"])||companies[i]} award: ${txt(d.Description)||txt(d["Award ID"])}`,summary:`Award amount ${txt(d["Award Amount"])} from ${txt(d["Awarding Agency"])}`,officialUrl:`https://www.usaspending.gov/award/${encodeURIComponent(txt(d["Award ID"]))}`,publishedAt:txt(d["Start Date"]),ticker:symbols[i],company:companies[i],officialProofType:"government_contract_award",officialProofStrength:"contract",accessionOrDocumentId:txt(d["Award ID"]),raw:d,receivedAt})); } finally{ clearTimeout(t); } } return rows; }
export async function runOfficialAnnouncementRun(input:OfficialAnnouncementInput={}){ const dryRun=input.dryRun!==false, runId=crypto.randomUUID(), receivedAt=new Date().toISOString(); const symbols=(input.symbols?.length?input.symbols:["NVDA","AMD","MSFT","GOOGL"]).map(s=>s.toUpperCase()); const companies=input.companyNames?.length?input.companyNames:["NVIDIA","Advanced Micro Devices","Microsoft","Alphabet"]; const keywords=input.keywords?.length?input.keywords:["product launch","guidance","contract","lawsuit","investigation","approval","recall"]; const max=Math.min(Math.max(Number(input.maxItemsPerSource??20),1),50), timeoutMs=input.timeoutMs??8000; const failures:Json[]=[], attempted:string[]=[]; const all:ReturnType<typeof signal>[]=[]; async function add(name:string, fn:()=>Promise<ReturnType<typeof signal>[]>) { attempted.push(name); try{ all.push(...await fn()); }catch(e){ failures.push({sourceName:name,safeErrorCategory:txt(e instanceof Error?e.message:e).startsWith("http_")?txt(e instanceof Error?e.message:e).slice(0,80):"source_fetch_failed_safely"}); }}
 await add("SEC EDGAR",()=>sec(symbols,companies,max,timeoutMs,receivedAt));
 await add("Company IR/newsroom allowlist",async()=>{ const rows=[] as ReturnType<typeof signal>[]; for(const f of COMPANY_FEEDS.filter(f=>symbols.includes(f.ticker))) rows.push(...await feed(`Company IR/newsroom: ${f.company}`,"company_ir_newsroom",f.url,"company_official_announcement",keywords,symbols,companies,max,timeoutMs,receivedAt).catch(()=>{failures.push({sourceName:f.company,safeErrorCategory:"source_fetch_failed_safely"}); return [];})); return rows; });
 await add("Federal Reserve",async()=>{ const urls=["https://www.federalreserve.gov/feeds/press_all.xml","https://www.federalreserve.gov/feeds/speeches.xml","https://www.federalreserve.gov/feeds/testimony.xml"]; const rows=[] as ReturnType<typeof signal>[]; for(const u of urls) rows.push(...await feed("Federal Reserve","federal_reserve",u,"fed_official_update",keywords,symbols,companies,max,timeoutMs,receivedAt).catch(()=>[])); return rows; });
 await add("Federal Register",()=>federalRegister(keywords,symbols,companies,max,timeoutMs,receivedAt));
 await add("openFDA/FDA",()=>feed("FDA official updates","fda_official","https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/recalls/rss.xml","fda_official_update",keywords.concat(companies),symbols,companies,max,timeoutMs,receivedAt).catch(()=>[]));
 attempted.push("DOJ/FTC"); failures.push({sourceName:"DOJ/FTC",safeErrorCategory:"disabled_needs_source_contract"});
 await add("USAspending",()=>usaSpending(companies,symbols,max,timeoutMs,receivedAt));
 if(process.env.SAM_API_KEY?.trim()) attempted.push("SAM.gov"); else failures.push({sourceName:"SAM.gov",safeErrorCategory:"skipped_missing_sam_api_key"});
 const r2=await getR2OperationalStatus().catch(()=>null); let rawStored=0; for(const s of all){ if(r2?.writeAvailable){ const key=`raw/official-announcements/${DAY()}/${runId}/${s.storyHash}.json`; const ref=await saveJsonToR2(key,s.raw,{source:"official-announcements",dataType:s.sourceType,runId}).then(x=>x?.r2Key??key).catch(()=>null); if(ref){ s.rawStorageRef=ref; rawStored++; }} if(!dryRun&&process.env.DATABASE_URL){ const existing=await prisma.rawSignal.findFirst({where:{OR:[{sourceUrl:s.officialUrl},{source:s.sourceName,title:s.title}]}}); if(!existing) await prisma.rawSignal.create({data:{source:s.sourceName,ticker:s.ticker,signalType:s.officialProofType,title:s.title,summary:s.summary,sourceUrl:s.officialUrl,importanceHint:"high",payload:redactSecrets(s) as Prisma.InputJsonValue}}); }}
 const clean=all.filter(s=>Number(s.entityMatchConfidence)>=55 && Boolean(s.ticker||s.company)); const clusters=input.clusters||[]; const attached=clean.filter(s=>clusters.some(c=>txt(c.primaryTicker||c.primary_ticker)===s.ticker || txt(c.canonicalTitle||c.canonical_title).toLowerCase().includes(txt(s.company).toLowerCase()))).length;
 return {ok:true,dryRun,confirmRun:input.confirmRun===true,runId,officialSourcesAttempted:attempted,officialProofSignalsCreated:clean.length,officialProofAttachedToClusters:attached,officialAnnouncementFailures:failures,officialAnnouncementSummary:{ok:true,sourcesAttempted:attempted.length,rawSignalsFound:all.length,cleanMappedOfficialSignals:clean.length,rawStoredInR2Count:rawStored,failures,sourceFailureNonBlocking:true},rawSignals:all.map(s=>({...s,raw:undefined,officialProofAvailable:Number(s.entityMatchConfidence)>=55,officialProofUrl:s.officialUrl,officialProofMissingReason:Number(s.entityMatchConfidence)>=55?null:"official source found but ticker/company mapping is not clean enough"})),rawStoredInR2Count:rawStored,rawDataStored:rawStored>0,noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}; }
