import { prisma } from "@/lib/db/client";
import { saveJsonToR2, getR2OperationalStatus } from "@/lib/r2-warehouse";
import { redactSecrets } from "@/lib/redact-secrets";

type Json = Record<string, unknown>;
type SourceFail = { source: string; reason: string };
export type PriceVolumeProof = {
  ticker: string; priceVolumeProofAvailable: boolean; cleanPriceVolumeProof: boolean; latestPrice: number|null; latestPriceSource: string|null; latestPriceReceiptUrl: string|null; volume: number|null; volumeSource: string|null; averageVolume: number|null; volumeRatio: number|null; priceChange1d: number|null; priceChange5d: number|null; priceChange20d: number|null; relativeToSectorOrETF: string|null; marketReactionStatus: "confirmed_reaction"|"no_clear_reaction"|"early_signal_possible"|"unavailable"; earlySignalPossible: boolean; proofCompleteness: "clean"|"partial"|"unavailable"; sourceUsed: string|null; attemptedSources: string[]; failedSources: SourceFail[]; unavailableReason: string|null; paidApiRequired: boolean; canFixWithoutPaidApi: boolean; capturedAt?: string|null; timestampFromProvider?: string|null; rawStoredInR2?: boolean; r2ObjectKey?: string|null; snapshotCreated?: boolean; skippedDuplicate?: boolean;
};
const RECEIPT_AV = "https://www.alphavantage.co/documentation/#latestprice";
const FMP_BASE = (process.env.FMP_BASE_URL?.trim() || "https://financialmodelingprep.com").replace(/\/api\/v3\/?$/, "");
const TICKER_RE = /[^A-Z0-9.:-]/g;
function ticker(v: unknown){ return String(v??"").trim().toUpperCase().replace(TICKER_RE,"").slice(0,16); }
function num(v: unknown){ const x = typeof v === "string" ? Number(v.replace(/,/g,"").replace(/%$/, "")) : typeof v === "number" ? v : NaN; return Number.isFinite(x) ? x : null; }
function safe(e: unknown){ return e instanceof Error ? e.message.replace(/[A-Za-z0-9_\-]{20,}/g,"[redacted]").slice(0,120) : "provider_failed_safe"; }
function daysOld(v: unknown){ const t=Date.parse(String(v??"")); return Number.isFinite(t)?(Date.now()-t)/86400000:Infinity; }
function marketDaysOk(v: unknown){ return daysOld(v) <= 8; }
function hasMove(p: Partial<PriceVolumeProof>){ return p.volume!=null || p.priceChange1d!=null || p.priceChange5d!=null || p.priceChange20d!=null; }
function classify(p: Partial<PriceVolumeProof> & { sourceUsed?: string|null; latestPriceReceiptUrl?: string|null; timestampFromProvider?: string|null; capturedAt?: string|null }, failed: SourceFail[], attempted: string[]): PriceVolumeProof {
 const latest=p.latestPrice??null; const stale=!marketDaysOk(p.timestampFromProvider ?? p.capturedAt); const clean=Boolean(latest!==null && p.latestPriceReceiptUrl && !stale && hasMove(p)); const partial=Boolean(latest!==null && p.latestPriceReceiptUrl && !stale && !clean);
 return { ticker: ticker(p.ticker), priceVolumeProofAvailable: clean||partial, cleanPriceVolumeProof: clean, latestPrice: latest, latestPriceSource:p.latestPriceSource??null, latestPriceReceiptUrl:p.latestPriceReceiptUrl??null, volume:p.volume??null, volumeSource:p.volumeSource??null, averageVolume:p.averageVolume??null, volumeRatio:p.volume!=null&&p.averageVolume?Number((p.volume/p.averageVolume).toFixed(4)):null, priceChange1d:p.priceChange1d??null, priceChange5d:p.priceChange5d??null, priceChange20d:p.priceChange20d??null, relativeToSectorOrETF:null, marketReactionStatus: clean ? "confirmed_reaction" : partial ? "early_signal_possible" : "unavailable", earlySignalPossible: partial || (!clean && latest===null), proofCompleteness: clean?"clean":partial?"partial":"unavailable", sourceUsed:p.sourceUsed??null, attemptedSources:attempted, failedSources:failed, unavailableReason: clean||partial?null:(stale?"stale_price_older_than_5_trading_days_rejected":"no_stored_snapshot_alpha_vantage_fmp_or_free_adapter_price_available"), paidApiRequired:false, canFixWithoutPaidApi:true, capturedAt:p.capturedAt??null, timestampFromProvider:p.timestampFromProvider??null, rawStoredInR2:p.rawStoredInR2, r2ObjectKey:p.r2ObjectKey??null, snapshotCreated:p.snapshotCreated, skippedDuplicate:p.skippedDuplicate };
}
export async function marketSnapshotTableExists(){ if(!process.env.DATABASE_URL) return false; try{ const r=await prisma.$queryRaw<Array<{exists:boolean}>>`select exists (select 1 from information_schema.tables where table_name='market_price_snapshots')`; return r[0]?.exists===true; }catch{return false;} }
async function latestStored(symbol:string){ if(!await marketSnapshotTableExists()) return null; const rows=await prisma.$queryRaw<Array<Json>>`select * from market_price_snapshots where ticker=${symbol} and latest_price is not null order by captured_at desc limit 1`; return rows[0]??null; }
async function insertSnapshot(row: Json){ if(!process.env.DATABASE_URL || !await marketSnapshotTableExists()) return {created:false,duplicate:false}; try{ await prisma.$executeRaw`insert into market_price_snapshots (ticker,provider,source_url,latest_price,currency,volume,average_volume,price_change_1d,price_change_5d,price_change_20d,previous_close,open,high,low,timestamp_from_provider,captured_at,market_session,raw_stored_in_r2,r2_object_key,data_quality,unavailable_reason) values (${row.ticker as string},${row.provider as string},${row.sourceUrl as string|null},${row.latestPrice as number|null},${row.currency as string|null},${row.volume as number|null},${row.averageVolume as number|null},${row.priceChange1d as number|null},${row.priceChange5d as number|null},${row.priceChange20d as number|null},${row.previousClose as number|null},${row.open as number|null},${row.high as number|null},${row.low as number|null},${new Date(String(row.timestampFromProvider))},${new Date(String(row.capturedAt))},${row.marketSession as string|null},${Boolean(row.rawStoredInR2)},${row.r2ObjectKey as string|null},${row.dataQuality as string},${row.unavailableReason as string|null}) on conflict (ticker,provider,timestamp_from_provider) do nothing`; const found=await latestStored(String(row.ticker)); return {created:true,duplicate:false,latest:found}; }catch(e){ if(String(e).includes("Unique")) return {created:false,duplicate:true}; return {created:false,duplicate:false,error:safe(e)}; } }
async function saveRaw(provider:string,symbol:string,raw:unknown,storeRaw=true){ if(!storeRaw) return {saved:false,key:null,reason:"storeRaw_false"}; const r2=await getR2OperationalStatus().catch(()=>null); if(!r2?.writeAvailable) return {saved:false,key:null,reason:"r2_unavailable"}; const key=`raw/market-price/${provider}/${symbol}/${new Date().toISOString().slice(0,10)}/${Date.now()}.json`; try{ const saved=await saveJsonToR2(key, raw, {source:provider,dataType:"market-price",symbol}); return {saved:true,key:saved?.r2Key??key,reason:null}; }catch{return {saved:false,key:null,reason:"r2_save_failed_safe"};} }
async function fetchJson(url:string){ const r=await fetch(url,{cache:"no-store"}); if(!r.ok) throw new Error(`http_${r.status}`); return await r.json(); }
async function alpha(symbol:string, storeRaw:boolean){ const raw=await fetchJson(`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${encodeURIComponent(symbol)}&apikey=${process.env.ALPHA_VANTAGE_API_KEY}`) as Json; const q=(raw["Global Quote"]??{}) as Json; if(ticker(q["01. symbol"])!==symbol) throw new Error(raw["Note"]?"alpha_vantage_quota_or_note":"alpha_vantage_ticker_mismatch_or_empty"); const latest=num(q["05. price"]); if(latest===null) throw new Error("alpha_vantage_latest_price_null_rejected"); const ts=new Date().toISOString(); const r2=await saveRaw("alpha-vantage",symbol,raw,storeRaw); return {ticker:symbol,provider:"alpha_vantage",sourceUrl:RECEIPT_AV,latestPrice:latest,currency:"USD",volume:num(q["06. volume"]),averageVolume:null,priceChange1d:num(q["10. change percent"]),priceChange5d:null,priceChange20d:null,previousClose:num(q["08. previous close"]),open:num(q["02. open"]),high:num(q["03. high"]),low:num(q["04. low"]),timestampFromProvider:ts,capturedAt:ts,marketSession:"latest_available",rawStoredInR2:r2.saved,r2ObjectKey:r2.key,dataQuality:"clean",unavailableReason:null}; }
async function fmp(symbol:string, storeRaw:boolean){ const url=`${FMP_BASE}/api/v3/quote/${encodeURIComponent(symbol)}?apikey=${process.env.FMP_API_KEY}`; const raw=await fetchJson(url) as unknown; const q=Array.isArray(raw)?raw[0] as Json:null; if(!q || ticker(q.symbol)!==symbol) throw new Error("fmp_ticker_mismatch_or_empty"); const latest=num(q.price); if(latest===null) throw new Error("fmp_latest_price_null_rejected"); const r2=await saveRaw("fmp",symbol,raw,storeRaw); const ts=new Date().toISOString(); return {ticker:symbol,provider:"fmp",sourceUrl:`${FMP_BASE}/api/v3/quote/${symbol}`,latestPrice:latest,currency:"USD",volume:num(q.volume),averageVolume:num(q.avgVolume),priceChange1d:num(q.changesPercentage),priceChange5d:null,priceChange20d:null,previousClose:num(q.previousClose),open:num(q.open),high:num(q.dayHigh),low:num(q.dayLow),timestampFromProvider:ts,capturedAt:ts,marketSession:"latest_available",rawStoredInR2:r2.saved,r2ObjectKey:r2.key,dataQuality:"clean",unavailableReason:null}; }
function fromSnapshot(r:Json, attempted:string[], failed:SourceFail[]): PriceVolumeProof { return classify({ticker:String(r.ticker),latestPrice:num(r.latest_price),latestPriceSource:String(r.provider),latestPriceReceiptUrl:String(r.source_url??`stored://market_price_snapshots/${r.ticker}`),volume:num(r.volume),volumeSource:String(r.provider),averageVolume:num(r.average_volume),priceChange1d:num(r.price_change_1d),priceChange5d:num(r.price_change_5d),priceChange20d:num(r.price_change_20d),sourceUsed:String(r.provider),capturedAt:r.captured_at?new Date(String(r.captured_at)).toISOString():null,timestampFromProvider:r.timestamp_from_provider?new Date(String(r.timestamp_from_provider)).toISOString():null,rawStoredInR2:Boolean(r.raw_stored_in_r2),r2ObjectKey:r.r2_object_key?String(r.r2_object_key):null}, failed, attempted); }
export async function getPriceVolumeProofForTicker(t:string, options:{storeRaw?:boolean; preferStored?:boolean}={}){ const symbol=ticker(t); const attempted:string[]=[]; const failed:SourceFail[]=[]; if(!symbol) return classify({ticker:""}, failed, attempted); attempted.push("market_price_snapshots"); const stored=await latestStored(symbol).catch(()=>null); if(stored){ const p=fromSnapshot(stored,attempted,failed); if(p.priceVolumeProofAvailable) return p; failed.push({source:"market_price_snapshots",reason:p.unavailableReason??"stored_snapshot_rejected"}); } else failed.push({source:"market_price_snapshots",reason:"no_usable_stored_snapshot"});
 if(process.env.ALPHA_VANTAGE_API_KEY){ attempted.push("alpha_vantage"); try{ const row=await alpha(symbol, options.storeRaw!==false); const ins=await insertSnapshot(row); return classify({...row,latestPriceSource:"Alpha Vantage GLOBAL_QUOTE",latestPriceReceiptUrl:RECEIPT_AV,volumeSource:"Alpha Vantage GLOBAL_QUOTE",sourceUsed:"alpha_vantage",snapshotCreated:ins.created,skippedDuplicate:ins.duplicate},failed,attempted); }catch(e){failed.push({source:"alpha_vantage",reason:safe(e)});} } else failed.push({source:"alpha_vantage",reason:"not_configured"});
 if(process.env.FMP_API_KEY){ attempted.push("fmp_quote"); try{ const row=await fmp(symbol, options.storeRaw!==false); const ins=await insertSnapshot(row); return classify({...row,latestPriceSource:"FMP quote",latestPriceReceiptUrl:String(row.sourceUrl),volumeSource:"FMP quote",sourceUsed:"fmp",snapshotCreated:ins.created,skippedDuplicate:ins.duplicate},failed,attempted); }catch(e){failed.push({source:"fmp_quote",reason:safe(e)});} } else failed.push({source:"fmp_quote",reason:"not_configured"});
 attempted.push("repo_approved_free_adapter","raw_signals_or_previous_run_snapshots"); return classify({ticker:symbol}, failed, attempted);
}
export async function runMarketSnapshotEar(input:Json={}){ const max=Math.max(1,Math.min(Number(input.maxTickers??20),20)); const provided=Array.isArray(input.tickers)?input.tickers.map(ticker).filter(Boolean):[]; let ticks=provided.slice(0,max); if(!ticks.length && process.env.DATABASE_URL){ const rows=await prisma.rawSignal.findMany({where:{ticker:{not:null}},orderBy:{receivedAt:"desc"},take:max}).catch(()=>[]); ticks=[...new Set(rows.map(r=>ticker(r.ticker)).filter(Boolean))].slice(0,max); } if(!ticks.length) ticks=["TSLA","AMD","MSFT","NVDA","META"].slice(0,max); const results=[]; for(const t of ticks) results.push(await getPriceVolumeProofForTicker(t,{storeRaw:input.storeRaw!==false})); return redactSecrets({ok:true,dryRun:input.dryRun!==false,tickersRequested:provided,tickersChecked:ticks,snapshotsCreated:results.filter(r=>r.snapshotCreated).length,snapshotsSkippedDuplicate:results.filter(r=>r.skippedDuplicate).length,priceVolumeProofAvailableCount:results.filter(r=>r.priceVolumeProofAvailable).length,unavailableCount:results.filter(r=>!r.priceVolumeProofAvailable).length,providerResults:results,r2StorageSummary:{rawStoredCount:results.filter(r=>r.rawStoredInR2).length,r2ObjectKeys:results.map(r=>r.r2ObjectKey).filter(Boolean).slice(0,5)},topSnapshots:results.filter(r=>r.priceVolumeProofAvailable).slice(0,10),unavailableReasons:results.filter(r=>!r.priceVolumeProofAvailable).map(r=>({ticker:r.ticker,reason:r.unavailableReason,failedSources:r.failedSources})),noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}); }
export async function runPriceVolumeProofRecovery(input:Json={}){ const max=Math.max(1,Math.min(Number(input.maxCandidates??20),50)); const explicit=Array.isArray(input.tickers)?input.tickers.map(ticker).filter(Boolean):[]; let ticks=explicit.slice(0,max); if(!ticks.length && process.env.DATABASE_URL){ const rows=await prisma.rawSignal.findMany({where:{ticker:{not:null}},orderBy:{receivedAt:"desc"},take:max}).catch(()=>[]); ticks=[...new Set(rows.map(r=>ticker(r.ticker)).filter(Boolean))].slice(0,max); } const proofs=[]; for(const t of ticks) proofs.push(await getPriceVolumeProofForTicker(t,{storeRaw:true})); const added=proofs.filter(p=>p.priceVolumeProofAvailable); return redactSecrets({ok:true,dryRun:input.dryRun!==false,candidatesInspected:ticks.length,tickersChecked:ticks,priceVolumeProofAddedCount:added.length,cleanPriceVolumeProofCount:added.filter(p=>p.cleanPriceVolumeProof).length,partialPriceVolumeProofCount:added.filter(p=>p.proofCompleteness==="partial").length,unavailableCount:proofs.length-added.length,proofAddedByTicker:Object.fromEntries(added.map(p=>[p.ticker,p])),stillMissingPriceVolume:proofs.filter(p=>!p.priceVolumeProofAvailable).map(p=>p.ticker),priceVolumeRecoveryDebug:proofs.map(p=>({ticker:p.ticker,sourceUsed:p.sourceUsed,attemptedSources:p.attemptedSources,failedSources:p.failedSources,unavailableReason:p.unavailableReason})),nextBestFix:added.length?"Stage 1 can now consume stored market_price_snapshots for these tickers.":"Configure or unthrottle Alpha Vantage/FMP, or seed real market_price_snapshots from an approved free adapter.",noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}); }
export async function priceVolumeDiagnostics(){ const exists=await marketSnapshotTableExists(); const latest=exists?await prisma.$queryRaw<Array<{ticker:string; captured_at:Date}>>`select ticker, max(captured_at) as captured_at from market_price_snapshots group by ticker order by max(captured_at) desc limit 20`.catch(()=>[]):[]; return redactSecrets({ok:true,marketSnapshotTableExists:exists,latestSnapshotCount:latest.length,latestTickersWithSnapshots:latest.map(x=>x.ticker),alphaVantageConfigured:Boolean(process.env.ALPHA_VANTAGE_API_KEY),alphaVantageQuotaStatus:process.env.ALPHA_VANTAGE_API_KEY?"configured_quota_checked_on_request":"not_configured",fmpConfigured:Boolean(process.env.FMP_API_KEY),fmpCurrentStatus:process.env.FMP_API_KEY?"configured_checked_on_request":"not_configured",approvedFreeAdapterAvailable:false,r2StorageAvailable:Boolean((await getR2OperationalStatus().catch(()=>null))?.writeAvailable),lastMarketSnapshotRunAt:null,lastPriceVolumeProofRunAt:null,commonUnavailableReasons:["no_usable_stored_snapshot","alpha_vantage_not_configured_or_quota","fmp_not_configured_or_empty","stale_price_older_than_5_trading_days_rejected"],nextBestFix:"Run Market Snapshot Ear for top proof-needed tickers; if unavailable, verify free provider keys and quotas.",noSecretsExposed:true,secretsRedacted:true}); }
