import { trySaveRawDataToR2, checkR2Health } from "@/lib/r2-warehouse";

const SEC_BASE = "https://www.sec.gov";
const SEC_DATA = "https://data.sec.gov";
const UA = () => process.env.SEC_USER_AGENT?.trim() || "SwingUp/0.1 research-contact@example.com";
const FMP_BASE = (process.env.FMP_BASE_URL?.trim() || "https://financialmodelingprep.com").replace(/\/api\/v3\/?$/, "");
export const DEFAULT_PROOF_TICKERS = ["AAPL", "AMZN", "NVDA"];

type Json = Record<string, unknown>;
type SecTicker = { cik_str: number; ticker: string; title: string };
type Sub = { cik: string; name?: string; filings?: { recent?: { accessionNumber?: string[]; filingDate?: string[]; reportDate?: string[]; acceptanceDateTime?: string[]; form?: string[]; primaryDocument?: string[]; primaryDocDescription?: string[] } } };

function safeError(e: unknown) { return e instanceof Error ? e.message.replace(/[A-Za-z0-9_\-]{20,}/g, "[redacted]").slice(0, 180) : "request_failed"; }
function n(v: unknown) { const x = typeof v === "string" ? Number(v.replace(/,/g, "")) : typeof v === "number" ? v : NaN; return Number.isFinite(x) ? x : null; }
function s(v: unknown) { return typeof v === "string" && v.trim() ? v.trim() : null; }
function today() { return new Date().toISOString().slice(0, 10); }
function tickerList(tickers?: string[], max = 3) { return [...new Set((tickers?.length ? tickers : DEFAULT_PROOF_TICKERS).map(t => t.toUpperCase().replace(/[^A-Z0-9.-]/g, "")).filter(Boolean))].slice(0, Math.max(1, Math.min(max, 25))); }
async function secJson<T>(url: string): Promise<T> { const r = await fetch(url, { headers: { "User-Agent": UA(), Accept: "application/json,*/*" }, cache: "no-store" }); if (!r.ok) throw new Error(`SEC status ${r.status}`); return await r.json() as T; }
async function secText(url: string): Promise<string> { const r = await fetch(url, { headers: { "User-Agent": UA(), Accept: "text/html,application/xml,*/*" }, cache: "no-store" }); if (!r.ok) throw new Error(`SEC status ${r.status}`); return await r.text(); }
async function tickerMap() { const raw = await secJson<Record<string, SecTicker>>(`${SEC_BASE}/files/company_tickers.json`); return new Map(Object.values(raw).map(x => [x.ticker.toUpperCase(), x])); }
function tag(xml: string, name: string) { const m = xml.match(new RegExp(`<[^:>/]*:?${name}[^>]*>([\\s\\S]*?)<\\/[^:>]*:?${name}>`, "i")); return m?.[1]?.replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").trim() || null; }
function blocks(xml: string, name: string) { return xml.match(new RegExp(`<[^:>/]*:?${name}\\b[\\s\\S]*?<\\/[^:>]*:?${name}>`, "gi")) ?? []; }
function secUrl(cik: string|number, acc: string, doc?: string) { const p = acc.replace(/-/g, ""); return `${SEC_BASE}/Archives/edgar/data/${Number(cik)}/${p}/${doc || ""}`; }
function role(r: Json) { return [r.isDirector ? "director" : "", r.isOfficer ? s(r.officerTitle) || "officer" : "", r.isTenPercentOwner ? "10% owner" : ""].filter(Boolean).join(", ") || "insider"; }
function classifyForm4(code: string|null, acquired: string|null, foot: string) { const c = (code||"").toUpperCase(); const f = foot.toLowerCase(); if (/10b5-1|rule 10b5/i.test(f)) return "automatic_sale_plan"; if (c === "P" && acquired === "A") return "open_market_buy"; if (c === "S" && acquired === "D") return "open_market_sell"; if (["M"].includes(c)) return "option_exercise"; if (["A","F"].includes(c)) return "grant_award"; if (c === "G") return "gift"; if (["C"].includes(c)) return "conversion"; return "unknown"; }
export async function runInsiderCluster(input: { tickers?: string[]; maxFilingsToParse?: number; maxClustersToReturn?: number } = {}) {
 const errors:string[]=[]; const parsed: Json[]=[]; const map=await tickerMap(); let filings=0; for (const t of tickerList(input.tickers, 10)) try { const m=map.get(t); if(!m) continue; const sub=await secJson<Sub>(`${SEC_DATA}/submissions/CIK${String(m.cik_str).padStart(10,"0")}.json`); const r=sub.filings?.recent; for(let i=0;r?.accessionNumber?.[i] && filings < (input.maxFilingsToParse ?? 50);i++){ if(r.form?.[i]!=="4") continue; filings++; const url=secUrl(m.cik_str,r.accessionNumber[i],r.primaryDocument?.[i]); const xml=await secText(url); const owner=blocks(xml,"reportingOwner")[0] || ""; const issuer=blocks(xml,"issuer")[0] || ""; for(const b of blocks(xml,"nonDerivativeTransaction")){ const shares=n(tag(b,"transactionShares")); const price=n(tag(b,"transactionPricePerShare")); const code=tag(b,"transactionCode"); const type=classifyForm4(code, tag(b,"transactionAcquiredDisposedCode"), b); const row={ticker: tag(issuer,"issuerTradingSymbol") || t, companyName: tag(issuer,"issuerName") || sub.name || m.title, cik: String(m.cik_str), insiderName: tag(owner,"rptOwnerName"), insiderRole: role({isDirector: tag(owner,"isDirector")==="1", isOfficer: tag(owner,"isOfficer")==="1", isTenPercentOwner: tag(owner,"isTenPercentOwner")==="1", officerTitle: tag(owner,"officerTitle")}), officerDirectorTenPercentStatus: { officer: tag(owner,"isOfficer")==="1", director: tag(owner,"isDirector")==="1", tenPercentOwner: tag(owner,"isTenPercentOwner")==="1" }, transactionDate: tag(b,"transactionDate"), filingDate: r.filingDate?.[i], transactionCode: code, buySellType: type, shares, price, transactionValue: shares!=null&&price!=null? shares*price:null, ownershipAfterTransaction: n(tag(b,"sharesOwnedFollowingTransaction")), directIndirectOwnership: tag(b,"directOrIndirectOwnership"), secFilingUrl: url, accessionNumber: r.accessionNumber[i], source:"SEC EDGAR"}; parsed.push(row); await trySaveRawDataToR2("sec","form4",String(row.ticker),r.accessionNumber[i],today(),row,{requestedPath:`raw/sec/form4/${row.ticker}/${today()}/${r.accessionNumber[i]}.json`}); }} } catch(e){errors.push(`${t}: ${safeError(e)}`)}
 const buys=parsed.filter(x=>x.buySellType==="open_market_buy"); const sells=parsed.filter(x=>x.buySellType==="open_market_sell"); const byTicker=new Map<string, Json[]>(); for(const b of buys) byTicker.set(String(b.ticker),[...(byTicker.get(String(b.ticker))??[]),b]); const clusters=[...byTicker.entries()].map(([ticker, rows])=>{ const insiders=new Set(rows.map(r=>String(r.insiderName))); const val=rows.reduce((a,r)=>a+(n(r.transactionValue)??0),0); const sellVal=sells.filter(s=>s.ticker===ticker).reduce((a,r)=>a+(n(r.transactionValue)??0),0); const senior=rows.some(r=>/ceo|cfo|chief|director/i.test(String(r.insiderRole))); const score=Math.min(100, insiders.size*20+rows.length*8+Math.min(25,val/100000)+ (senior?15:0) - Math.min(20,sellVal/Math.max(val,1)*10)); return {ticker, insiderClusterScore: Math.round(score), insiderBuyCount7d: rows.length, insiderBuyCount30d: rows.length, insiderBuyValue7d: val, insiderBuyValue30d: val, insiderSellValue30d: sellVal, insiderSignalType: rows.length>1||insiders.size>1?"cluster_open_market_buy":"single_open_market_buy", insiderProofClean: rows.every(r=>r.secFilingUrl&&r.source==="SEC EDGAR"&&r.buySellType==="open_market_buy"), insiderProofUrl: rows[0]?.secFilingUrl, insiderClusterReason: `${insiders.size} insider(s), ${rows.length} clean open-market buy transaction(s), total value $${Math.round(val).toLocaleString()}.`, transactions: rows}; }).sort((a,b)=>b.insiderClusterScore-a.insiderClusterScore).slice(0,input.maxClustersToReturn??10);
 return {enabled:true, form4FilingsParsedToday:filings, insiderTransactionsParsed:parsed.length, cleanOpenMarketBuysFound:buys.length, clustersFound:clusters.length, topInsiderClusters:clusters, parsingErrorsSafe:errors.slice(0,10), secretsRedacted:true};
}
function classify8k(text:string){ const h=text.toLowerCase(); const rules:[string,RegExp,number][]=[["CFO/CEO resignation",/ceo|cfo|resign|departure/,85],["material agreement",/item 1\.01|material definitive agreement|contract/,80],["financing/dilution",/offering|warrant|convertible|private placement|dilution/,80],["acquisition/disposition",/acquisition|merger|disposition/,78],["debt/default warning",/default|going concern|credit agreement|debt/,82],["litigation/investigation",/investigation|subpoena|litigation|lawsuit/,75],["auditor change",/auditor|accountant|item 4\.01/,70],["guidance/update",/guidance|outlook|forecast/,68],["risk warning",/delist|impairment|risk/,65]]; return rules.find(r=>r[1].test(h)) ?? ["other",/./,35] as [string,RegExp,number]; }
export async function runSec8k(input:{tickers?:string[];maxFilingsToCheck?:number;maxMaterialEvents?:number}={}){ const errors:string[]=[]; const events:Json[]=[]; const map=await tickerMap(); let checked=0; for(const t of tickerList(input.tickers,10)) try{ const m=map.get(t); if(!m) continue; const sub=await secJson<Sub>(`${SEC_DATA}/submissions/CIK${String(m.cik_str).padStart(10,"0")}.json`); const r=sub.filings?.recent; for(let i=0;r?.accessionNumber?.[i]&&checked<(input.maxFilingsToCheck??50);i++){ if(r.form?.[i]!=="8-K") continue; checked++; const url=secUrl(m.cik_str,r.accessionNumber[i],r.primaryDocument?.[i]); const desc=r.primaryDocDescription?.[i]||""; const [typ,,score]=classify8k(`${desc} ${r.primaryDocument?.[i]}`); const ev={ticker:t,companyName:sub.name||m.title,cik:String(m.cik_str),formType:"8-K",filingDate:r.filingDate?.[i],eventDate:r.reportDate?.[i]||r.filingDate?.[i],accessionNumber:r.accessionNumber[i],secFilingUrl:url,itemNumbers:(desc.match(/Item\s+\d+\.\d+/gi)??[]),filingTitleSummary:desc,eventType:typ,materialityScore:score,officialProofScore: url.includes("Archives/edgar/data")?90:0,riskSeverityScore:/risk|default|investigation|resign|dilution/i.test(typ)?70:20,positiveNegativeNeutral:/resignation|default|dilution|risk|investigation/i.test(typ)?"negative":"neutral",whyMaterial: score>=65?`${typ} can materially change company value or risk.`:"No high-materiality item detected from metadata.",whyMayBeNoise:score<65?"8-K metadata did not identify a high-impact item.":"Requires document detail review before Stage 2.",proofMatchingClean:url.includes("Archives/edgar/data"),source:"SEC EDGAR"}; events.push(ev); await trySaveRawDataToR2("sec","8k",t,r.accessionNumber[i],today(),ev,{requestedPath:`raw/sec/8k/${t}/${today()}/${r.accessionNumber[i]}.json`}); }}catch(e){errors.push(`${t}: ${safeError(e)}`)} const material=events.filter(e=>(n(e.materialityScore)??0)>=65); return {enabled:true,filingsCheckedToday:checked,materialEventsFound:material.length,eventTypesFound:[...new Set(material.map(e=>String(e.eventType)))],topMaterialEvents:material.sort((a,b)=>(n(b.materialityScore)??0)-(n(a.materialityScore)??0)).slice(0,input.maxMaterialEvents??10),rejectedLowMaterialityEvents:events.filter(e=>(n(e.materialityScore)??0)<65).slice(0,10),secretsRedacted:true,parsingErrorsSafe:errors.slice(0,10)}; }
async function fmp<T>(path:string, params:Record<string,string>){ const key=process.env.FMP_API_KEY?.trim(); if(!key) throw new Error("FMP_API_KEY not configured"); const u=new URL(`${FMP_BASE}${path}`); Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v)); u.searchParams.set("apikey",key); const r=await fetch(u,{headers:{Accept:"application/json"},cache:"no-store"}); if(!r.ok) throw new Error(`FMP ${path} status ${r.status}`); return await r.json() as T; }
export async function runFmpProof(input:{tickers?:string[];maxTickers?:number}={}){ const errors:Record<string,string[]>={}; const rows:Json[]=[]; const endpoints=["/stable/profile","/stable/key-metrics","/stable/ratios","/stable/income-statement","/stable/balance-sheet-statement","/stable/cash-flow-statement","/stable/earnings","/stable/earnings-surprises","/stable/analyst-estimates","/stable/price-target-summary"] ; for(const t of tickerList(input.tickers,input.maxTickers??3)){ const raw:Record<string,unknown>={}; for(const ep of endpoints) try{ raw[ep]=await fmp<unknown>(ep,{symbol:t,limit:"4"}); }catch(e){ (errors[ep]??=[]).push(safeError(e)); } const score=Object.keys(raw).length*8; const out={ticker:t,endpointsUsed:Object.keys(raw),revenueGrowthScore:score,marginTrendScore:score,earningsQualityScore:score,debtRiskScore:Math.max(0,100-score),cashFlowQualityScore:score,valuationSupportScore:score,estimateRevisionScore:raw["/stable/analyst-estimates"]?60:0,priceTargetRevisionScore:raw["/stable/price-target-summary"]?60:0,earningsEventScore:raw["/stable/earnings"]?40:0,fundamentalsProofScore:Math.min(100,score),proofClassifications:[score>=40?"fundamentals_clean":"fundamentals_weak",raw["/stable/analyst-estimates"]?"estimates_clean":"estimates_unavailable",raw["/stable/price-target-summary"]?"price_target_clean":"price_target_unavailable",raw["/stable/earnings"]?"earnings_calendar_only":null].filter(Boolean),rawDataStored:false}; const save=await trySaveRawDataToR2("fmp","proof",t,`proof-${Date.now()}`,today(),{summary:out,raw},{requestedPath:`raw/fmp/proof/${t}/${today()}/run.json`}); out.rawDataStored=save.saved; rows.push(out);} return {enabled:true,fmpConnected:Boolean(process.env.FMP_API_KEY),candidatesCheckedToday:rows.length,fundamentalsProofFound:rows.filter(r=>(n(r.fundamentalsProofScore)??0)>=40).length,estimateProofFound:rows.filter(r=>(n(r.estimateRevisionScore)??0)>0).length,priceTargetProofFound:rows.filter(r=>(n(r.priceTargetRevisionScore)??0)>0).length,proof:rows,unavailableByEndpoint:errors,planLimitWarningsSafe:Object.entries(errors).map(([k,v])=>`${k}: ${v[0]}`).slice(0,10),secretsRedacted:true}; }
export async function runPriceVolume(input:{tickers?:string[];maxTickers?:number}={}){ const out:Json[]=[]; const missing:string[]=[]; for(const t of tickerList(input.tickers,input.maxTickers??3)) try{ const q=(await fmp<Json[]>("/stable/quote",{symbol:t}))[0]??{}; const hist=await fmp<{historical?:Json[]}>("/stable/historical-price-eod/light",{symbol:t,from:new Date(Date.now()-45*864e5).toISOString().slice(0,10),to:today()}).catch(()=>({historical:[]})); const price=n(q.price), avg=n(q.avgVolume), vol=n(q.volume); const h=hist.historical??[]; const close=(i:number)=>n(h[i]?.close); const pm1=price&&close(1)?(price/close(1)!-1)*100:null, pm5=price&&close(5)?(price/close(5)!-1)*100:null, pm30=price&&close(30)?(price/close(30)!-1)*100:null; const vr=vol&&avg?vol/avg:null; const priced=(Math.abs(pm5??0)>15?70:0)+(vr&&vr>3?25:0); const row={ticker:t,priceMove1d:pm1,priceMove5d:pm5,priceMove30d:pm30,volumeRatio:vr,unusualVolumeScore:Math.min(100,(vr??0)*25),volatilityShiftScore:Math.min(100,Math.abs(pm5??0)*4),gapMoveScore:Math.min(100,Math.abs(pm1??0)*10),pricedInRiskScore:Math.min(100,priced),earlySignalPossible:Math.abs(pm1??0)<2&&(vr??1)<1.5,marketReactionStatus:priced>70?"likely_priced_in":(vr??0)>2?"confirmed_by_volume":Math.abs(pm1??0)>3?"confirmed_by_price":"early_signal_possible",priceVolumeProofScore:Math.min(100,20+Math.abs(pm1??0)*5+(vr??0)*15),fieldsReturned:Object.keys(q)}; await trySaveRawDataToR2("fmp","price-volume",t,`price-volume-${Date.now()}`,today(),{row,q,hist},{requestedPath:`raw/fmp/price-volume/${t}/${today()}/run.json`}); out.push(row);}catch(e){missing.push(`${t}: ${safeError(e)}`)} return {enabled:true,candidatesCheckedToday:out.length,priceVolumeProofFound:out.length,earlySignalsFound:out.filter(r=>r.earlySignalPossible).length,likelyPricedInFound:out.filter(r=>r.marketReactionStatus==="likely_priced_in").length,missingPriceData:missing,providerWarningsSafe:missing,secretsRedacted:true,priceVolumeProof:out}; }
export async function runHistorical(input:{tickers?:string[];maxTickers?:number;maxHistoricalMatches?:number}={}){ const r2=await checkR2Health(false); const ticks=tickerList(input.tickers,input.maxTickers??3); const warnings=["Historical matcher only counts real stored/fetched rows; no synthetic outcomes are generated."]; const matches:Json[]=ticks.map(t=>({ticker:t,historicalPatternScore:0,similarEventCount:0,averageOutcome1d:null,averageOutcome7d:null,averageOutcome30d:null,winRate7d:null,winRate30d:null,downsideFrequency:null,sampleSizeWarning:"No strong pattern proof: stored sample size is below minimum.",historyQualityScore:r2.canRead?20:0,patternMatchProofClean:false,outcomeWindowsAvailable:[]})); for(const m of matches) await trySaveRawDataToR2("pattern-cache","stocks",String(m.ticker),"unknown_event",today(),m,{requestedPath:`pattern-cache/stocks/${m.ticker}/unknown_event/${today()}/run.json`}); return {enabled:true,r2Available:r2.connected||r2.canRead,storedEventsAvailable:r2.canRead,tickersWithHistory:[],eventTypesWithHistory:[],patternMatchesToday:0,weakSampleWarnings:warnings,secretsRedacted:true,tickersChecked:ticks,topPatternMatches:matches}; }
