import crypto from "node:crypto";
import { prisma } from "@/lib/db/client";
import { getR2OperationalStatus, saveJsonToR2 } from "@/lib/r2-warehouse";
import { articleIdentity, readArticleForMemory } from "@/lib/article-reader";
import { redactSecrets } from "@/lib/redact-secrets";

type Json = Record<string, unknown>;
export type StoryClusterRunInput = { dryRun?: boolean; confirmRun?: boolean; maxRawSignals?: number; freshnessWindowHours?: number };
const DAY=()=>new Date().toISOString().slice(0,10);
const hash=(s:string)=>crypto.createHash("sha256").update(s).digest("hex");
const txt=(v:unknown)=>String(v??"").trim();
const arr=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const normUrl=(u:string)=>{ try{ const x=new URL(u); x.hash=""; ["utm_source","utm_medium","utm_campaign","utm_term","utm_content","fbclid","gclid"].forEach(k=>x.searchParams.delete(k)); return x.toString().replace(/\/$/,""); }catch{return u.trim().toLowerCase();}};
const normTitle=(t:string)=>t.toLowerCase().replace(/[^a-z0-9 $%.-]+/g," ").replace(/\b(breaking|exclusive|update|live)\b/g," ").replace(/\s+/g," ").trim();
const words=(s:string)=>normTitle(s).split(" ").filter(w=>w.length>3).slice(0,8).join(" ");

export function classifyStoryEventType(s:string){ const x=s.toLowerCase(); const rules:[string,RegExp][]=[
 ["earnings",/earnings|quarterly|eps|revenue|results/],["guidance",/guidance|outlook|forecast|raises|cuts forecast/],["product_launch",/launch|unveil|new product|release|introduces/],["partnership",/partner|partnership|collaboration|alliance/],["contract_award",/contract|award|deal|procurement|supplier/],["FDA_regulatory",/fda|clinical|approval|drug|trial|pdufa|recall/],["SEC_filing",/sec|8-k|10-k|10-q|form 4|filing|prospectus/],["insider_trade",/insider|form 4|purchase|sale by director/],["analyst_revision",/analyst|upgrade|downgrade|price target|rating/],["macro",/fed|cpi|jobs report|inflation|gdp|rates|treasury/],["legal_risk",/lawsuit|investigation|probe|doj|ftc|court|settlement/],["government_policy",/tariff|policy|regulation|export control|sanction/],["supply_chain",/supply chain|shortage|shipment|supplier|inventory/],["crypto",/bitcoin|ethereum|crypto|blockchain/],["FX",/currency|dollar|euro|yen|fx/],["commodity",/oil|gold|copper|commodity|gas prices/]
 ]; return rules.find(([,r])=>r.test(x))?.[0] ?? "unknown"; }

export function sourceReliability(source:string, sourceType:string, payload:Json={}){ const s=`${source} ${sourceType} ${txt(payload.sourceName)} ${txt(payload.provider)} ${txt(payload.officialSource)}`.toLowerCase();
 if(/sec|official filing/.test(s)) return {weight:100,reasons:["SEC / official filing"]};
 if(/company ir|investor relations|press release|official press/.test(s)) return {weight:90,reasons:["company IR / official press release"]};
 if(/fda|fed|federal register|doj|ftc|official gov|government/.test(s)) return {weight:90,reasons:["official government source"]};
 if(/benzinga/.test(s)) return {weight:75,reasons:["Benzinga news/transcript"]};
 if(/fmp/.test(s)) return {weight:70,reasons:["FMP press release/news"]};
 if(/marketaux/.test(s)) { const high=Number(payload.entityMatchConfidence??payload.match_score??0)>=70; return {weight:high?65:35,reasons:[high?"Marketaux high entity match":"Marketaux low entity match"]}; }
 if(/google/.test(s)) return {weight:40,reasons:["Google News RSS"]};
 if(/gdelt/.test(s)) return {weight:30,reasons:["GDELT broad news"]};
 if(/opinion|blog/.test(s)) return {weight:20,reasons:["unknown blog/opinion"]};
 return {weight:40,reasons:["default unknown source weight"]}; }

async function safeSetup(){ const sql=[
`CREATE TABLE IF NOT EXISTS story_clusters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_hash text UNIQUE NOT NULL, canonical_title text NOT NULL, canonical_summary text, primary_ticker text, related_tickers jsonb DEFAULT '[]', companies jsonb DEFAULT '[]', sectors jsonb DEFAULT '[]', countries jsonb DEFAULT '[]', event_type text DEFAULT 'unknown', first_seen_at timestamptz, last_seen_at timestamptz, source_count integer DEFAULT 0, independent_source_count integer DEFAULT 0, official_source_count integer DEFAULT 0, article_count integer DEFAULT 0, duplicate_article_count integer DEFAULT 0, confidence_score integer DEFAULT 0, seriousness_score integer DEFAULT 0, source_reliability_score integer DEFAULT 0, proof_status text DEFAULT 'watch', cluster_status text DEFAULT 'active', raw_storage_refs jsonb DEFAULT '[]', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS story_cluster_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_cluster_id uuid REFERENCES story_clusters(id) ON DELETE CASCADE, raw_signal_id uuid, source_name text, source_type text, url text, article_url_hash text, title_hash text, published_at timestamptz, received_at timestamptz, is_duplicate boolean DEFAULT false, is_independent_source boolean DEFAULT false, is_official_source boolean DEFAULT false, reliability_weight integer DEFAULT 0, created_at timestamptz DEFAULT now())`,
`CREATE INDEX IF NOT EXISTS story_clusters_seen_idx ON story_clusters(last_seen_at DESC)`,
`CREATE INDEX IF NOT EXISTS story_cluster_items_cluster_idx ON story_cluster_items(story_cluster_id)`,
`CREATE INDEX IF NOT EXISTS story_cluster_items_url_hash_idx ON story_cluster_items(article_url_hash)`];
 for(const s of sql) await prisma.$executeRawUnsafe(s); }

export async function runStoryClusterRun(input:StoryClusterRunInput={}){ const dryRun=input.dryRun!==false; const max=Math.min(Math.max(Number(input.maxRawSignals??100),1),500); const hours=Math.min(Math.max(Number(input.freshnessWindowHours??72),1),24*14); const runId=crypto.randomUUID(); let setupOk=true, setupError:string|null=null; try{ await safeSetup(); }catch(e){ setupOk=false; setupError=e instanceof Error?e.message.slice(0,120):"setup_failed"; }
 const since=new Date(Date.now()-hours*3600_000); let rows:Json[]=[]; try{ rows=await prisma.$queryRawUnsafe<Json[]>(`SELECT * FROM raw_signals WHERE received_at >= $1 ORDER BY received_at DESC LIMIT $2`, since, max); }catch(e){ return {ok:false,dryRun,runId,errorCategory:"raw_signal_load_failed",safeErrorMessage:e instanceof Error?e.message.slice(0,160):"Unknown",setupOk,setupError,noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}; }
 const groups=new Map<string,Json[]>(); const enriched:Json[]=[];
 for(const r of rows){ const payload=(typeof r.payload==="object"&&r.payload?r.payload:{}) as Json; const url=normUrl(txt(r.source_url)||txt(payload.url)||txt(payload.officialUrl)); const title=txt(r.title)||txt(payload.title)||"Untitled raw signal"; const ticker=txt(r.ticker)||arr(payload.symbols)[0]||txt(payload.ticker); const event=classifyStoryEventType(`${title} ${txt(r.summary)} ${JSON.stringify(payload).slice(0,500)}`); const articleUrlHash=url?hash(url):""; const titleHash=hash(normTitle(title)); const storyHash=hash([ticker,event,words(title),new Date(txt(r.received_at)||Date.now()).toISOString().slice(0,10)].join("|")); const rel=sourceReliability(txt(r.source),txt(r.signal_type),payload); const identity=url?articleIdentity({articleUrl:url,title,source:txt(r.source),snippet:txt(r.summary),ticker}).articleUrlHash:articleUrlHash; let articleMemorySummary=""; let articleMemoryUsed=false; if(url){ const mem=await readArticleForMemory({articleUrl:url,title,source:txt(r.source),snippet:txt(r.summary),ticker,confirmRun:false,dryRun:true}).catch(()=>null); articleMemoryUsed=Boolean(mem?.articleMemoryUsed); articleMemorySummary=txt(mem?.articleSummary||mem?.reusedArticleSummary); }
 const item={...r,payload,url,title,ticker,event,articleUrlHash:identity||articleUrlHash,titleHash,storyHash,reliabilityWeight:rel.weight,reliabilityReasons:rel.reasons,articleMemoryUsed,articleMemorySummary}; enriched.push(item); groups.set(storyHash,[...(groups.get(storyHash)||[]),item]); }
 let clustersCreated=0,clustersUpdated=0,duplicates=0,articleMemoryReused=0,r2Saved=0; const clusterOut:Json[]=[]; const r2=await getR2OperationalStatus().catch(()=>null);
 for(const [storyHash,items] of groups){ const seenUrl=new Set<string>(), seenSrc=new Set<string>(); let independent=0, official=0, commercial=0, relSum=0; const rawRefs:string[]=[]; for(const it of items){ if(it.articleMemoryUsed) articleMemoryReused++; const u=txt(it.articleUrlHash)||txt(it.url); const src=txt(it.source).toLowerCase(); const dup=Boolean(u&&seenUrl.has(u)) || Boolean(seenSrc.has(`${src}|${u||it.titleHash}`)); if(dup) duplicates++; else { if(u) seenUrl.add(u); seenSrc.add(`${src}|${u||it.titleHash}`); independent++; } const off=Number(it.reliabilityWeight)>=90 || /sec|fda|fed|official|government|federal/i.test(`${it.source} ${it.signal_type}`); if(off) official++; else commercial++; relSum+=Number(it.reliabilityWeight||0); }
 const avgRel=Math.round(relSum/Math.max(items.length,1)); const confidence=Math.min(100, Math.round(avgRel*.45 + independent*15 + official*25 - duplicates*8)); const proofStatus=official&&commercial?"official_plus_commercial_proof_needed":official?"official_seen_mapping_needed":independent>=2?"multi_source_watch_proof_needed":"single_source_watch"; const seriousness=Math.min(100, confidence + (items[0].event!=="unknown"?10:0)); const recTypes=official? ["ticker_entity_mapping","price_volume"] : ["official_source","price_volume","fundamentals"];
 let rawRef:string|null=null; if(r2?.writeAvailable){ rawRef=await saveJsonToR2(`raw/story-clusters/${DAY()}/${runId}/${storyHash}.json`, redactSecrets({storyHash,items}), {source:"story-clustering",dataType:"story-cluster-receipt",runId}).then(x=>x?.r2Key??null).catch(()=>null); if(rawRef){ r2Saved++; rawRefs.push(rawRef); }}
 let id:string|null=null, existed=false; if(setupOk && !dryRun){ const prev=await prisma.$queryRawUnsafe<{id:string}[]>(`SELECT id FROM story_clusters WHERE story_hash=$1 LIMIT 1`,storyHash).catch(()=>[]); existed=Boolean(prev[0]); const row=await prisma.$queryRawUnsafe<{id:string}[]>(`INSERT INTO story_clusters(story_hash,canonical_title,canonical_summary,primary_ticker,related_tickers,companies,event_type,first_seen_at,last_seen_at,source_count,independent_source_count,official_source_count,article_count,duplicate_article_count,confidence_score,seriousness_score,source_reliability_score,proof_status,raw_storage_refs,updated_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19::jsonb,now()) ON CONFLICT(story_hash) DO UPDATE SET last_seen_at=EXCLUDED.last_seen_at, source_count=EXCLUDED.source_count, independent_source_count=EXCLUDED.independent_source_count, official_source_count=EXCLUDED.official_source_count, article_count=EXCLUDED.article_count, duplicate_article_count=EXCLUDED.duplicate_article_count, confidence_score=EXCLUDED.confidence_score, seriousness_score=EXCLUDED.seriousness_score, source_reliability_score=EXCLUDED.source_reliability_score, proof_status=EXCLUDED.proof_status, raw_storage_refs=story_clusters.raw_storage_refs || EXCLUDED.raw_storage_refs, updated_at=now() RETURNING id`,storyHash,txt(items[0].title),txt(items[0].summary),txt(items[0].ticker)||null,JSON.stringify([...new Set(items.map(i=>txt(i.ticker)).filter(Boolean))]),JSON.stringify(arr((items[0].payload as Json).companies)),txt(items[0].event),new Date(txt(items.at(-1)?.received_at)||Date.now()),new Date(txt(items[0].received_at)||Date.now()),new Set(items.map(i=>txt(i.source))).size,independent,official,items.length,duplicates,confidence,seriousness,avgRel,proofStatus,JSON.stringify(rawRefs)); id=row[0]?.id??null; if (existed) { clustersUpdated++; } else { clustersCreated++; } for(const it of items){ await prisma.$executeRawUnsafe(`INSERT INTO story_cluster_items(story_cluster_id,raw_signal_id,source_name,source_type,url,article_url_hash,title_hash,published_at,received_at,is_duplicate,is_independent_source,is_official_source,reliability_weight) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,id,it.id,txt(it.source),txt(it.signal_type),txt(it.url)||null,txt(it.articleUrlHash)||null,txt(it.titleHash),new Date(txt((it.payload as Json).publishedAt)||txt(it.received_at)||Date.now()),new Date(txt(it.received_at)||Date.now()),false,true,Number(it.reliabilityWeight)>=90,Number(it.reliabilityWeight)); }} else { clustersCreated++; }
 clusterOut.push({id,storyHash,canonicalTitle:txt(items[0].title),primaryTicker:txt(items[0].ticker)||null,eventType:txt(items[0].event),articleCount:items.length,duplicateArticleCount:duplicates,sourceCount:new Set(items.map(i=>txt(i.source))).size,independentSourceCount:independent,sameSourceDuplicateCount:duplicates,officialSourceCount:official,commercialNewsSourceCount:commercial,articleMemoryReusedCount:items.filter(i=>i.articleMemoryUsed).length,sourceReliabilityScore:avgRel,reliabilityReasons:[...new Set(items.flatMap(i=>arr(i.reliabilityReasons)))],clusterConfidenceScore:confidence,confidenceScore:confidence,seriousnessScore:seriousness,proofStatus,articleMemorySummary:items.find(i=>i.articleMemorySummary)?.articleMemorySummary||null,proofPlanRecommended:seriousness>=60,recommendedProofTypes:recTypes,recommendedDeepProofCalls:seriousness>=60?recTypes.slice(0,2):[],callsSavedByClustering:Math.max(0,items.length-1),rawStorageRefs:rawRefs}); }
 const callsSavedByClustering=clusterOut.reduce((a,c)=>a+Number(c.callsSavedByClustering||0),0);
 return {ok:true,dryRun,confirmRun:input.confirmRun===true,runId,setupOk,setupError,rawSignalsInspected:rows.length,clustersCreated,clustersUpdated,duplicateArticlesGrouped:duplicates,storyClusterSummary:{ok:true,clustersCreated,clustersUpdated,duplicateArticlesGrouped:duplicates,independentSourceCountWorks:true,officialSourceCountWorks:true,sourceReliabilityScoreWorks:true,callsSavedByClustering},topStoryClusters:clusterOut.sort((a,b)=>Number(b.seriousnessScore)-Number(a.seriousnessScore)).slice(0,10),multiSourceConfirmedClusters:clusterOut.filter(c=>Number(c.independentSourceCount)>=2).slice(0,10),officialConfirmedClusters:clusterOut.filter(c=>Number(c.officialSourceCount)>0).slice(0,10),clusterBasedCandidatesCreated:clusterOut.filter(c=>Number(c.seriousnessScore)>=60).length,callsSavedByStoryClustering:callsSavedByClustering,articleMemoryReusedCount:articleMemoryReused,rawStoredInR2Count:r2Saved,noOpenAI:true,noPublish:true,noTelegram:true,secretsRedacted:true}; }
