import Link from "next/link";

const ledgerRows = [
  { date: "2026-06-18", action: "Buy Candidate", ticker: "SHOP", alertPrice: "$64.20", result: "+2.4% tracked", oneDay: "pending", sevenDay: "pending", thirtyDay: "pending", status: "open", href: "/public/alerts/shop-margin-reset" },
  { date: "2026-06-17", action: "Watch", ticker: "AMD", alertPrice: "$128.40", result: "flat", oneDay: "+0.3%", sevenDay: "pending", thirtyDay: "pending", status: "neutral", href: "#" },
  { date: "2026-06-16", action: "Speculative Buy Candidate", ticker: "SOFI", alertPrice: "$8.92", result: "+5.1% tracked", oneDay: "+1.2%", sevenDay: "pending", thirtyDay: "pending", status: "win", href: "#" },
  { date: "2026-06-15", action: "Sell Review", ticker: "NFLX", alertPrice: "$682.10", result: "-1.8% tracked", oneDay: "-0.7%", sevenDay: "pending", thirtyDay: "pending", status: "open", href: "#" },
  { date: "2026-06-14", action: "Avoid", ticker: "XYZ", alertPrice: "$21.35", result: "risk avoided", oneDay: "-2.0%", sevenDay: "-4.6%", thirtyDay: "pending", status: "loss", href: "#" },
  { date: "2026-06-13", action: "No Action", ticker: "META", alertPrice: "$505.00", result: "no trade tracked", oneDay: "n/a", sevenDay: "n/a", thirtyDay: "n/a", status: "neutral", href: "#" },
];

export default function PublicLedgerPage() {
  return <div className="page"><section className="hero trust-hero"><div><div className="eyebrow">Public ledger</div><h1>Accountability for research alerts.</h1><p>This placeholder ledger uses mock data to show how public alert tracking will appear. Results are for transparency, not a guarantee that future alerts will perform the same way.</p><div className="button-row"><Link className="button primary" href="/methodology">How scoring works</Link><Link className="button" href="/risk-disclaimer">Risk disclaimer</Link></div></div><div className="card"><div className="metric"><span>Ledger data</span><strong>Mock placeholder</strong></div><div className="metric"><span>Purpose</span><strong>Public accountability</strong></div><div className="metric"><span>Advice status</span><strong>Not financial advice</strong></div></div></section><section className="card ledger-card"><div className="ledger-header"><div><h2>Tracked alerts</h2><p>Delayed and placeholder fields shown until live alert tracking is connected.</p></div><span className="badge">Mock data</span></div><div className="table-wrap"><table className="table ledger-table"><thead><tr><th>Alert date</th><th>Action</th><th>Ticker</th><th>Price at alert</th><th>Current tracked result</th><th>1D</th><th>7D</th><th>30D</th><th>Status</th><th>Public alert</th></tr></thead><tbody>{ledgerRows.map((row) => <tr key={`${row.date}-${row.ticker}`}><td>{row.date}</td><td>{row.action}</td><td><strong>{row.ticker}</strong></td><td>{row.alertPrice}</td><td>{row.result}</td><td>{row.oneDay}</td><td>{row.sevenDay}</td><td>{row.thirtyDay}</td><td><span className={`badge ledger-status ledger-status-${row.status}`}>{row.status}</span></td><td><Link className="ledger-link" href={row.href}>View</Link></td></tr>)}</tbody></table></div></section></div>;
}
