CREATE TABLE IF NOT EXISTS article_memory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  article_url_hash text UNIQUE NOT NULL,
  normalized_url text NOT NULL,
  source_name text,
  title text,
  title_hash text,
  ticker_symbols jsonb DEFAULT '[]',
  company_names jsonb DEFAULT '[]',
  article_text_available boolean DEFAULT false,
  article_text_read boolean DEFAULT false,
  article_text_read_at timestamptz,
  article_summary text,
  relevance_summary text,
  catalyst_summary text,
  proof_summary text,
  risk_summary text,
  entities_detected jsonb DEFAULT '[]',
  topics_detected jsonb DEFAULT '[]',
  article_relevance_score integer DEFAULT 0,
  article_quality_score integer DEFAULT 0,
  article_duplicate_of text,
  first_seen_at timestamptz DEFAULT now(),
  last_seen_at timestamptz DEFAULT now(),
  read_count integer DEFAULT 0,
  reused_count integer DEFAULT 0,
  raw_text_storage_ref text,
  error_category text,
  error_message_safe text
);
CREATE INDEX IF NOT EXISTS article_memory_seen_idx ON article_memory(last_seen_at DESC);
